### PR TITLE
Bump locarna to latest 1.x

### PR DESCRIPTION
**Pull request by bernt-matthias**
Tests will only work with https://github.com/galaxyproject/galaxy/pull/14998 .. or we temporarily remove the `expect_num_outputs` from some tests.

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
Mh, test still works, ready to merge?

**Comment by bernt-matthias** [comment]
Let me test something..

**Comment by bernt-matthias** [comment]
No tests are executed: `Exception: The tool locarna_pairwise targets version 21.09 of Galaxy, you should upgrade Galaxy to ensure proper functioning of this tool.`

We should update the CI over here :) I will open a PR

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
ACE! Danke dir!

**Pull request merged**
