### PR TITLE
WIP: init commit lncpro - working process

### PR DESCRIPTION
**Pull request by AGoepfert**

### CODE REVIEW

**Comment by smithcr** [comment]
not quite ready yet :)

**Comment by bgruening** [comment]
please ping me for a review if you feel like it ... :)

**Comment by bgruening** [comment]
xref: https://github.com/bgruening/galaxytools/issues/161

**Comment by AGoepfert** [comment]
@bgruening there is the pull request - please review and have a look at proteinortho

**Comment by AGoepfert** [comment]
I wrapped the tools: 
- image (70% finished)
- lncPro (70% finished - no tool_dependency)
- PileOMeth (80% finished)
- ProteinOrtho (tool dependency not working)
- Quast (70% finished)
- samblaster (tool dependency not working)

**Comment by smithcr** [comment]
PileOMeth - selecting CHH/CHG in advanced options does not seem to produce these extra files...

**Comment by bgruening** [comment]
All the tools are already integrated as single PR. Thanks @AGoepfert and @smithcr !

**Pull request closed without merging**
