### PR TITLE
Eteri-master for graphclust

### PR DESCRIPTION
**Pull request by mmiladi**

### CODE REVIEW

**Comment by mmiladi** [comment]
@eteriSokhoyan Could you please check the travis erros?

**Comment by mmiladi** [comment]
@eteriSokhoyan If you have changed the output file format, then the test files must also change. The error is this:
```
Failed to find 'CLUSTER  2  CM_SCORE  86.6  MODEL     1.2  ORIGID  RF00641_rep.2_AC208187.2/29806-29886_82        ORIGHEAD  RF00641_rep.2   ' in history data. (lines_diff=0):
```

**Comment by eteriSokhoyan** [comment]
@mmiladi  ah, right, i completely forgot about the test, sorry, i will fix it now.

**Comment by mmiladi** [comment]
@bgruening PR finally passed the tests. Could you please have a look and merge. Thanks!

**Comment by mmiladi** [comment]
@bgruening What are we waiting for :D

**Comment by mmiladi** [comment]
Thanks much!

**Pull request merged**
