### PR TITLE
np-likeness-scorer

### PR DESCRIPTION
**Pull request by HassanAmr**
added .shed.yml and modified tool according to the new bioconda package

### CODE REVIEW

**Comment by HassanAmr** [comment]
Hi @bgruening ,

Who should be the owner?
Is everything else alright?

**Comment by bgruening** [comment]
test-data are missing here :(

**Comment by HassanAmr** [comment]
Sorry I missed that. I will prepare a test case for it.

**Comment by bgruening** [comment]
thanks

**Pull request merged**
