### PR TITLE
Remove Prinseq wrapper and point to tools-iuc wrapper

### PR DESCRIPTION
**Pull request by bebatut**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by bebatut** [comment]
Can you deprecated it on TTS, pls? Thanks

**Comment by bgruening** [comment]
Done! I have seen that you have one on MTS. Can you deprecate this one as well? I guess than we are finished with prinseq.

**Comment by bebatut** [comment]
Done (I had some weird issues with this one)

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
