### PR TITLE
Add a recipe for installing version 20141125 of the fiji package.

### PR DESCRIPTION
**Pull request by gregvonkuster**
I'll have a tool following shortly after this gets merged.  Thanks!

### CODE REVIEW

**Comment by bgruening** [comment]
LGTM, the OS-X installation looks scary, but if this works! I have no clue about OS-X.
@gregvonkuster if you can please add `.shed.yml` files to every repository. This makes it easier to upload to the TTS.

Thanks!
Bjoern

**Comment by erasche** [comment]
@gregvonkuster for your reference, the `.shed.yml` docs are here: http://galaxy-iuc-standards.readthedocs.org/en/latest/best_practices/shed_yml.html

**Comment by gregvonkuster** [comment]
@bgruening @erasche Thanks for the pointers on .shed.yml - I didn't see any of these in the other packages repositories in galaxytools repo, so I didn't know if I should add them.  Can you confirm that you want .shed.yml files for each package repo and I'll get them added quickly!  Thanks!!

**Comment by gregvonkuster** [comment]
@bgruening Do you want the imagej2 directory committed as a subdirectory of your current image_processing directory, or do you want it at the same level as image_processing?  Thanks!

**Comment by bgruening** [comment]
@gregvonkuster `.shed.yml` is pretty new and I'm lacking behind in creating those :(
If you can please create one. 
Under `image_processing` is fine I guess.

Thanks,
Bjoern

**Pull request merged**
