### PR TITLE
Upgrade Galaxy ML to 0.10.0

### PR DESCRIPTION
**Pull request by anuprulez**
Fix failing tests for almost all ML tools

ping @bgruening @kxk302

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @anuprulez for working on this!

**Comment by anuprulez** [comment]
I think all tests passed except for a few where file size > 1MB

```
tools/sklearn/test-data/ml_vis01.html
tools/sklearn/test-data/ml_vis02.html
tools/sklearn/test-data/ml_vis03.html
tools/sklearn/test-data/ml_vis04.html
tools/sklearn/test-data/ml_vis05.html
tools/sklearn/test-data/model_fit01
tools/sklearn/test-data/searchCV03
```

These files are more than 1 MB in size but less than 2 MB. The first 5 test-data files contain Plotly plots which are usually bigger. What do you think about these files?

ping @bgruening @kxk302 @paulzierep Thanks!

**Comment by paulzierep** [comment]
I did close to nothing, wow @anup, thats a lot of work !

**Comment by bgruening** [comment]
Wow, nice. Lets not care about the output size here. I will deploy those tools manually.

If you are all ok, I will merge and deploy?

**Comment by paulzierep** [comment]
> I think all tests passed except for a few where file size > 1MB
> 
> ```
> tools/sklearn/test-data/ml_vis01.html
> tools/sklearn/test-data/ml_vis02.html
> tools/sklearn/test-data/ml_vis03.html
> tools/sklearn/test-data/ml_vis04.html
> tools/sklearn/test-data/ml_vis05.html
> tools/sklearn/test-data/model_fit01
> tools/sklearn/test-data/searchCV03
> ```
> 
> These files are more than 1 MB in size but less than 2 MB. The first 5 test-data files contain Plotly plots which are usually bigger. What do you think about these files?
> 
> ping @bgruening @kxk302 @paulzierep Thanks!

the ml_vis*.html tests and model_fit01 only compare the size, we could just check the size, without using the actual file, using `has_size` or compare with (md5/checksum) ? any preference ? 
the searchCV03 is used as input, that one we would need to reduce.

**Comment by anuprulez** [comment]
I would love to see this merged :+1: 

Once these tools are available, we should verify all ML GTN tutorials with the latest version of these tools.

**Comment by bgruening** [comment]
I pushed them, hopefully all are uploaded.

I got this error "Repository [stacking_ensemble_models] does not exist in the targeted Tool Shed." .. what tool is that. The ID looks strange. There is a bug somewhere here.

**Comment by kxk302** [comment]
> I did close to nothing, wow @anup, thats a lot of work !

Same here! Just got back from vacation and was catching up with everything. Thanks a lot @anuprulez!

**Comment by anuprulez** [comment]
> stacking_ensemble_models

It could be this tool `[sklearn_stacking_ensemble_models](https://toolshed.g2.bx.psu.edu/repository/browse_repository?id=27b9dc6b09687b74)` but in `bgruening/galaxytools/tools/sklearn`, there is a tool with `stacking_ensemble_models` ID. 

I hope they both are same!

**Pull request merged**
