### PR TITLE
Bump Imagej2 tools to Fiji lifeline version 20170530

### PR DESCRIPTION
**Pull request by gregvonkuster**
@bgruening @ThomasWollmann The only approach I've found for testing these Java tools with planemo is to run this command...
```
$ planemo test ~galaxytools/imagej2/galaxytools/tools/image_processing/imagej2/imagej2_analyze_skeleton.xml
```
...which will block due to the issues with the local job runner.  While the test is blocking, copy the Galaxy environment created by planemo to a directory for testing.  This Galaxy environment directory can then be used as the value of the ```--galaxy_root``` parameter for ```planemo test...```.  I then comment out the problem line in the local job runner here https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/local.py#L108 for testing in with that Galaxy environment and everything works.

Some tools pass with this PR, and some are broken.  Namely the analyze_skeleton tool and all bunwarpj tools are broken.  These tools use plugins that were imported in a certain way in the Jython scripts with the older Fiji release, and I've not had time to figure out how the Jython imports need to be changed for this new release.

So with this PR, the following tools pass functional tests...
```
imagej2_adjust_threshold_binary.xml
imagej2_analyze_particles_binary.xml
imagej2_binary_to_edm.xml
imagej2_create_image.xml
imagej2_enhance_contrast.xml
imagej2_find_edges.xml
imagej2_find_maxima.xml
imagej2_make_binary.xml
imagej2_math.xml
imagej2_noise.xml
imagej2_shadows.xml
imagej2_sharpen.xml
imagej2_skeletonize3d.xml
imagej2_smooth.xml
imagej2_watershed_binary.xml
```
...and the following tools fail functional tests.
```
imagej2_analyze_skeleton.xml
imagej2_bunwarpj_adapt_transform.xml
imagej2_bunwarpj_align.xml
imagej2_bunwarpj_compare_elastic_raw.xml
imagej2_bunwarpj_compare_elastic.xml
imagej2_bunwarpj_compare_raw.xml
imagej2_bunwarpj_compose_elastic.xml
imagej2_bunwarpj_compose_raw_elastic.xml
imagej2_bunwarpj_compose_raw.xml
imagej2_bunwarpj_convert_to_raw.xml
imagej2_bunwarpj_elastic_transform.xml
imagej2_bunwarpj_raw_transform.xml
```
I'll try to get the tools with failing tests corrected, but it will be at least a couple of weeks before I can get back to them.  I'll fix these tools in separate PRs.

### CODE REVIEW

**Comment by gregvonkuster** [comment]
@bgruening @ThomasWollmann I just figured out the fix for the ```imagej2_analyze_skeleton``` tool, so it is now passing tests and only the bunwarpj tools are broken.

**Comment by bgruening** [comment]
Thanks a lot @gregvonkuster for working on this. dev has some changes/fixes to the local runner, maybe that helps in testing? I added a commit.

**Comment by gregvonkuster** [comment]
@bgruening I just used the Galaxy instance downloaded by planemo, which I assume will use the changes to the local job runner when they are available.  But as of today, I had to comment out the problem line in the runner.

**Comment by gregvonkuster** [comment]
I won't be able to look at the bunwarpj fixes for about 2 weeks, so it would be good to not hold up this PR waiting for them. I'll open a separate PR for them.

**Comment by gregvonkuster** [comment]
@bgruening @ThomasWollmann This commit https://github.com/bgruening/galaxytools/pull/896/commits/b08f0e6d1546caaf627b21f8c94044285d5d5b9c fixes all bUnwarpJ tools, so all Fiji tools should now be functionally correct with the new 2017 Fiji lifeline version.

**Comment by bgruening** [comment]
That is fantastic! Greg I finally found time to test this as well. I was able to get it to work with `planemo t --job_config_file /home/bag/projects/code/galaxy/config/job_conf.xml ` And Job conf was configured to use ht-condor with:

```
<job_conf>
    <plugins>
        <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="4"/>
        <plugin id="condor" type="runner" load="galaxy.jobs.runners.condor:CondorJobRunner" />
        <plugin id="pulsar_embedded" type="runner" load="galaxy.jobs.runners.pulsar:PulsarEmbeddedJobRunner">
          <param id="pulsar_config">/home/bag/projects/code/galaxy/config/pulsar_app.yml</param>
        </plugin>
    </plugins>
    <destinations default="condor2"><!-- for IT testing use "condor"-->
        <destination id="local" runner="local"/>
        <destination id="condor2" runner="condor">
        </destination>
        </destinations>
        <tools>
            <tool id="upload1" destination="local" />
        </tools>

</job_conf>
```

**Comment by gregvonkuster** [comment]
Awesome!  Thanks for posting the job config info!  :)

**Comment by bgruening** [comment]
You still need to install ht-condor but I'm sure this is so easy under OSX :( It was super easy on Ubuntu.

**Comment by bgruening** [comment]
Btw. TS upload is running :)

**Pull request merged**
