### PR TITLE
Move "ep" outside custom flavour also in command.

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix bug introduced in commit f1c0bd85086a7a2dbe125a251a509aef4f754794.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks.

**Comment by nsoranzo** [comment]
@bgruening Can you update the MTS when you have time, please?

**Comment by bgruening** [comment]
Done!

**Comment by nsoranzo** [comment]
Thanks!

**Pull request merged**
