### PR TITLE
Fix mapping of some databases for uniprot_rest_interface

### LINKED ISSUE #412: UniProt ID mapping and retrieval : [Errno 2] No such file or directory: './output'
Hi

I am trying to run UniProt from this toolset. using option to Map: UniProt id to Ensembl Genome Transcript. I ran into this error.

Error:
Fatal error: Exit code 2 ()
usage: uniprot.py map [-h] [--format FORMAT] f t [inp] [out]
uniprot.py map: error: argument inp: can't open './output': [Errno 2] No such file or directory: './output'

Command: 
cut -f 1 /Users/thankia/tools/galaxy-release_15.07/database/files/002/dataset_2455.dat > id_file.tabular && /Users/thankia/Downloads/galaxytools-master/tools/uniprot_rest_interface/uniprot.py map ACC+ID id_file.tabular ./output

Thanks

Anil

### PR DESCRIPTION
**Pull request by nsoranzo**
Fix #412.

Also cleanup the Python code and update test data.
Remove tool from blacklist.

Ping @anilthanki.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @nsoranzo! Be warned I was not able to use this tool with large sets of ids. I always get a timeout. It seems that uniprot is limiting the access at some point.

**Comment by nsoranzo** [comment]
Thanks @bgruening, we'll see how it goes! Can you push to MTS, that is not enabled in your repo yet.

**Comment by bgruening** [comment]
Pushed!

**Comment by anilthanki** [comment]
Thanks @bgruening

**Pull request merged**
