### PR TITLE
Update chipseeker to v1.18.0

### PR DESCRIPTION
**Pull request by mblue9**
And add ignore upstream and downstream options

### CODE REVIEW

**Comment by mblue9** [comment]
This is giving the (conda?) error 

` Error: package or namespace load failed for \u2018ChIPseeker\u2019 in dyn.load(file, DLLpath = DLLpath, ...):
|  unable to load shared object '/home/travis/conda/envs/mulled-v1-f40ed08976033d9c499bc6be361b7ec6ff2c3b359ec3d60c8357822ed340e7ac/lib/R/library/data.table/libs/datatable.so':
|  libgfortran.so.3: cannot open shared object file: No such file or directory`

**Comment by nsoranzo** [comment]
Can you try to modify `.travis.yml` for this repo as below?
```diff
diff --git a/.travis.yml b/.travis.yml
index d8c196e..58cc944 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -82,7 +82,7 @@ install:
   - conda install -y -c conda-forge conda=4.5.12
   - planemo --version
   - conda --version
-  - /home/travis/conda/bin/conda create -v -y --override-channels --channel iuc --channel bioconda --channel conda-forge --channel defaults --name mulled-v1-bb17a71839952990a701d9be96e6ded0cc4945e074406f3782c26da156b2e8d7 deepvariant=0.4.1 samtools=1.3.1
+  - /home/travis/conda/bin/conda create -v -y --override-channels --channel iuc --channel conda-forge --channel bioconda --channel defaults --name mulled-v1-bb17a71839952990a701d9be96e6ded0cc4945e074406f3782c26da156b2e8d7 deepvariant=0.4.1 samtools=1.3.1
   - git diff --quiet "$TRAVIS_COMMIT_RANGE" -- ; GIT_DIFF_EXIT_CODE=$?
   - |
     if [ "$GIT_DIFF_EXIT_CODE" -gt 1 ] ; then
@@ -120,10 +120,10 @@ script:
   - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
   - |
     if [ -s changed_tools_chunk.list ]; then
-        planemo test --conda_dependency_resolution --conda_auto_install --conda_channels iuc,bioconda,conda-forge,defaults --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" $(cat changed_tools_chunk.list)
+        planemo test --conda_dependency_resolution --conda_auto_install --conda_channels iuc,conda-forge,bioconda,defaults --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" $(cat changed_tools_chunk.list)
     elif [ -s changed_repositories_chunk.list ]; then
         while read -r DIR; do
-            planemo test --conda_dependency_resolution --conda_auto_install --conda_channels iuc,bioconda,conda-forge,defaults --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" "$DIR"
+            planemo test --conda_dependency_resolution --conda_auto_install --conda_channels iuc,conda-forge,bioconda,defaults --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" "$DIR"
         done < changed_repositories_chunk.list
     fi
   # Killing background sleep loop
```

**Comment by mblue9** [comment]
Ok thanks @nsoranzo, I have made those changes.

**Comment by bgruening** [comment]
Merci!

**Comment by mblue9** [comment]
Thanks for the merge!

**Pull request merged**
