### PR TITLE
Sortmerna fix command options

### PR DESCRIPTION
**Pull request by loraine-gueguen**
Hi,
I fix a bug in command options used for paired inputs.

### CODE REVIEW

**Comment by bgruening** [comment]
@loraine-gueguen thanks! I have really a PDF here were they write `--paried-end` :(

**Comment by nsoranzo** [comment]
@loraine-gueguen For future reference, you don't need to increase the tool version for bug fixes like this one.

**Comment by loraine-gueguen** [comment]
@nsoranzo ok

**Comment by loraine-gueguen** [comment]
@bgruening Will this new version be automatically pushed on the toolshed ?

**Pull request merged**
