### PR TITLE
applies the new conventions for imaging tools agreed at BioHackEU23

### PR DESCRIPTION
**Pull request by kostrykin**
xref https://github.com/elixir-europe/biohackathon-projects-2023/blob/main/16/conventions.md

### CODE REVIEW

**Comment by bgruening** [comment]
Nice, ready to merge when you are!

**Comment by kostrykin** [comment]
> Nice, ready to merge when you are!

@bgruening ready! 🚀

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
can you maybe increse the diff-size for cellprofiler4

> Collection element AS_09125_050116030001_D03f00d0_Overlay of collection pipeline_output:  different than expected
Expected file size of 168221+-0 found 182983

**Comment by kostrykin** [comment]
> can you maybe increse the diff-size for cellprofiler4
> 
> > Collection element AS_09125_050116030001_D03f00d0_Overlay of collection pipeline_output:  different than expected
> > Expected file size of 168221+-0 found 182983

@bgruening sorry I have absolutely no idea what you mean :)

**Comment by bgruening** [comment]
Cellprofiler 4 has in its test some check for the file size and this is failing here, because the size changed.

**Comment by kostrykin** [comment]
@sunyi000 can you maybe have a look at this?

**Comment by sunyi000** [comment]
> @sunyi000 can you maybe have a look at this?

i think it's line 148 of cellprofiler.xml, change the number to 182983

**Comment by bgruening** [comment]
There are 3 other tests with the same problem.

**Comment by kostrykin** [comment]
seems to be fine now

**Comment by bgruening** [comment]
Thanks.

**Comment by kostrykin** [comment]
The new tool versions are not found by `update-tool.py` from the [usegalaxy-eu/usegalaxy-eu-tools](https://github.com/usegalaxy-eu/usegalaxy-eu-tools) repo.

For example:

```
python scripts/update-tool.py --owner bgruening --name cp_cellprofiler4 imaging.yaml
INFO:root:Fetching updates for bgruening/cp_cellprofiler4
```

I guess this is due to the following [error in the CI](https://github.com/bgruening/galaxytools/actions/runs/6750447857/job/18353202904):

> Unsuccessful tests found, inspect the 'All tool test results' artifact for details.

> Errored Tests
> ❌ cp_mask_image (Test #1)
> Execution Problem:
> `Input staging problem: History not found`

Strangely the error was *not* reported by the [PR CI](https://github.com/bgruening/galaxytools/actions/runs/6749705220/job/18352542745).

I have no clue what "Input staging problem: History not found" means, any ideas? @bgruening

**Pull request merged**
