### PR TITLE
Update PharmCAT to 1.7.0

### PR DESCRIPTION
**Pull request by whaleyr**
We have released a new version of PharmCAT and published the docker image to Docker Hub.

### CODE REVIEW

**Comment by bgruening** [comment]
@whaleyr very cool, thanks a lot. I think we need to update the test data. Can you take a look please if that makes sense?

**Comment by whaleyr** [comment]
@bgruening Yes, can do. Will update the test data soon.

**Comment by bgruening** [comment]
I hope I updated it correctly :)
Read to merge from my side. Let me know :)

**Review by bgruening — APPROVED** [review]

**Comment by whaleyr** [comment]
Looks correct to me, thanks for doing that.

I'm still working on getting the `planemo` [test environment working](https://github.com/bgruening/galaxytools#running-the-tests) properly on my local machine, but it's having some troubles with the hdf5 dependency. I'll keep working on it.

**Comment by bgruening** [comment]
> I'm still working on getting the planemo [test environment working](https://github.com/bgruening/galaxytools#running-the-tests) properly on my local machine, but it's having some troubles with the hdf5 dependency. I'll keep working on it.

let me know if you need help

**Comment by bgruening** [comment]
Tool will be in the ToolShed in 10min and will be automatically updated on Sunday on the European Galaxy server.

**Comment by whaleyr** [comment]
Thanks very much, we'll have another update in the near future but I'm going to try to get my testing working before I submit that one.

**Comment by markwoon** [comment]
@bgruening Tried to use planemo to test this but I'm getting 

```
Exception: Failed to install Galaxy via command [if [ -d .venv ]; then GALAXY_VIRTUAL_ENV=.venv; else GALAXY_VIRTUAL_ENV=/xxx/.planemo/gx_venv_3; fi && export GALAXY_VIRTUAL_ENV && if [ ! -e "$GALAXY_VIRTUAL_ENV" ]; then /xxx/galaxytools/planemo/bin/python3 -m venv $GALAXY_VIRTUAL_ENV; echo "Created virtualenv"; fi && if [ -e "$GALAXY_VIRTUAL_ENV" ]; then . "$GALAXY_VIRTUAL_ENV"/bin/activate; echo "Activated a virtualenv for Galaxy"; echo "$VIRTUAL_ENV"; else echo "Failed to activate virtualenv."; fi && COMMON_STARTUP_ARGS=; $(grep -q 'skip-venv' run_tests.sh) && COMMON_STARTUP_ARGS="--dev-wheels"; export COMMON_STARTUP_ARGS; echo "Set COMMON_STARTUP_ARGS to ${COMMON_STARTUP_ARGS}" && ./scripts/common_startup.sh ${COMMON_STARTUP_ARGS}]
```

Any ideas how to resolve this?

**Comment by bgruening** [comment]
> ./scripts/common_startup.sh: 2: set: Illegal option -

That is interesting. The line is here: https://github.com/galaxyproject/galaxy/blob/dev/scripts/common_startup.sh#L2

Are you using bash?

**Comment by markwoon** [comment]
I'm using `tcsh`, but it shouldn't matter since the script itself is using `/bin/sh`, right?

**Comment by bgruening** [comment]
It should not, but maybe that is a symlink on your machine? The error is just irritating. Why should `set -e` be an illegal option?

**Comment by markwoon** [comment]
TIL: https://serverfault.com/a/193297/382472

I'm using Ubuntu 18 and `/bin/sh` is symlinked to `/bin/dash` .

I tested just this:

```
#!/bin/sh
set -e
echo "hello"
```

And this works fine.  So I don't think that's the problem as well.

What I'm not familiar with is line 5: `. ./scripts/common_startup_functions.sh`  - what does the initial `.` do?

**Comment by bgruening** [comment]
`.` is a shortcut for `source` 

Can you please try to use explicitly bash? Maybe https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425?permalink_comment_id=3799230#gistcomment-3799230


I tested on Ubuntu but I see this:

```
bag@bag:~/projects/code/galaxy$ ll /bin/bash
-rwxr-xr-x 1 root root 1396520 Jan  6 17:23 /bin/bash*
```

And it works.

**Comment by markwoon** [comment]
I changed `/bin/sh` to point to `/bin/bash` and it did not make a difference...

**Comment by markwoon** [comment]
Can you tell me where the file is called from?  I can try to do some debugging.

**Comment by bgruening** [comment]
From the galaxy directory. You can simply do

> ./scripts/common_startup.sh

**Comment by bgruening** [comment]
> I changed `/bin/sh` to point to `/bin/bash` and it did not make a difference...

its better to change that back I think. Not sure what will break this Ubuntu ;)

**Comment by markwoon** [comment]
But where is the galaxy directory?

I'm looking in my venv dir (`/planemo/lib/python3.6/site-packages`) and I see a `galaxy` dir, but there's no `scripts` dir there.

**Comment by bgruening** [comment]
Oh, I see you are not using your own clone. Ok so if you do not use your own Galaxy checkout, look into your HOME/.planemo/ I think this is where it ends up.

You can also use `planemo test --galaxy_root /home/user/galaxy/`

**Comment by markwoon** [comment]
The problem was that the file was using windows EOF (I'm running Ubuntu in a VM on Windows).

Once I got past that problem, I saw:
```
2022-05-10 13:32:04,498 INFO  [test_driver] 2 active after stopping embedded server
Traceback (most recent call last):
  File "/tmp/tmp_agc3gse/galaxy-dev/./scripts/functional_tests.py", line 127, in <module>
    driver_util.drive_test(find_test_driver())
  File "/tmp/tmp_agc3gse/galaxy-dev/lib/galaxy_test/driver/driver_util.py", line 1187, in drive_test
    sys.exit(test_driver.run())
  File "/tmp/tmp_agc3gse/galaxy-dev/lib/galaxy_test/driver/driver_util.py", line 982, in run
    raise e
  File "/tmp/tmp_agc3gse/galaxy-dev/lib/galaxy_test/driver/driver_util.py", line 978, in run
    success = nose_config_and_run()
  File "/tmp/tmp_agc3gse/galaxy-dev/lib/galaxy_test/driver/driver_util.py", line 364, in nose_config_and_run
    result = run(test_config)
  File "/tmp/tmp_agc3gse/galaxy-dev/lib/galaxy_test/base/nose_util.py", line 18, in run
    tests = loader.loadTestsFromNames(test_config.testNames)
  File "/xxx/.planemo/gx_venv_3/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/xxx/.planemo/gx_venv_3/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/xxx/.planemo/gx_venv_3/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
    return self.suiteClass(ContextList(tests, context=module))
  File "/xxx/.planemo/gx_venv_3/lib/python3.10/site-packages/nose/suite.py", line 428, in __call__
    return self.makeSuite(tests, context, **kw)
  File "/xxx/.planemo/gx_venv_3/lib/python3.10/site-packages/nose/suite.py", line 475, in makeSuite
    suite = self.suiteClass(
  File "/xxx/.planemo/gx_venv_3/lib/python3.10/site-packages/nose/suite.py", line 159, in __init__
    super(ContextSuite, self).__init__(tests)
  File "/xxx/.planemo/gx_venv_3/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/usr/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/xxx/.planemo/gx_venv_3/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
Testing complete. HTML report is in "/xxx/galaxytools/tool_test_output.html".
Cannot locate xUnit report [/tmp/tmp_agc3gse/xunit.xml] for tests - required to build planemo report and summarize tests.
Traceback (most recent call last):
  File "/xxx/galaxytools/planemo/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/planemo/cli.py", line 98, in handle_blended_options
    return f(*args, **kwds)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/planemo/commands/cmd_test.py", line 82, in cli
    return_value = test_runnables(ctx, runnables, original_paths=uris, **kwds)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/planemo/engine/test.py", line 35, in test_runnables
    return_value = run_in_config(ctx, config, **kwds)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/planemo/galaxy/test/actions.py", line 116, in run_in_config
    _check_test_outputs(xunit_report_file_tracker, structured_report_file_tracker)
  File "/xxx/galaxytools/planemo/lib/python3.10/site-packages/planemo/galaxy/test/actions.py", line 330, in _check_test_outputs
    raise Exception(message)
Exception: Cannot locate xUnit report [/tmp/tmp_agc3gse/xunit.xml] for tests - required to build planemo report and summarize tests.
```

I believe this is because I used python 3.10.  Once I downgraded to python 3.9, it worked.  I don't think 3.6 works either.  It would be a good idea to document this.

**Pull request merged**
