### PR TITLE
Update salmon v1.9.0

### PR DESCRIPTION
**Pull request by gallardoalba**
This PR updates salmon. In addition it improves index generation by enabling decoy-aware transcriptome, according with https://salmon.readthedocs.io/en/latest/salmon.html#preparing-transcriptome-indices-mapping-based-mode

### CODE REVIEW

**Comment by gallardoalba** [comment]
Not sure why it is failing, I didn't modify the .shed.xml  file @bgruening

**Comment by bgruening** [comment]
I see a broken XML in alevin. Planemo lint will show you.

**Comment by gallardoalba** [comment]
> I see a broken XML in alevin. Planemo lint will show you.

Ah, thanks a lot!

**Comment by gallardoalba** [comment]
Dot not merge, I need to fix an error.

**Comment by gallardoalba** [comment]
This is the current error, but it is strange because also the non-modified XML file seems to fail:

```
Traceback (most recent call last): File "/home/laptop/Galaxy/galaxy/lib/galaxy/jobs/runners/__init__.py", line 629, in _finish_or_resubmit_job job_wrapper.finish( File "/home/laptop/Galaxy/galaxy/lib/galaxy/jobs/__init__.py", line 1853, in finish self._finish_dataset(output_name, dataset, job, context, final_job_state, remote_metadata_directory) File "/home/laptop/Galaxy/galaxy/lib/galaxy/jobs/__init__.py", line 1671, in _finish_dataset dataset.datatype.set_meta(dataset, overwrite=False) File "/home/laptop/Galaxy/galaxy/lib/galaxy/datatypes/tabular.py", line 1613, in set_meta for line in dataset_fh: File "/home/laptop/miniconda3/envs/_galaxy_/lib/python3.8/codecs.py", line 322, in decode (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 1: invalid start byte
```

**Comment by gallardoalba** [comment]
This is the error:` Timed out after 900.25 seconds waiting on tool test run`, but I don't think is a tool problem @bgruening

**Comment by bgruening** [comment]
It could mean that Galaxy has been waiting for conda for too long and that the dependencies are conflicting ... I restarted lets see..

**Comment by bgruening** [comment]
Ist alevin fry the single cell component?

**Comment by gallardoalba** [comment]
> Ist alevin fry the single cell component?

Yes, according the developers, despite Alevin will be maintained for a while, it will be replaced by Alevin-fry.

**Comment by bgruening** [comment]
Ok good to know. Maybe we can replace this tool here at some point.

**Pull request merged**
