### PR TITLE
IntaRNA v3.3.1 + new option "--outPairwise"

### PR DESCRIPTION
**Pull request by martin-raden**
Hi @bgruening 
please have a look if the additional (optional) `--outPairwise` argument is correctly integrated into the xml.

Thanks,
Martin

### CODE REVIEW

**Review by gallardoalba — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks!

**Comment by bgruening** [comment]
@gallardoalba feel free to merge PRs.

**Comment by gallardoalba** [comment]
> @gallardoalba feel free to merge PRs.

I have not the right for merging the PRs in this repo I think

**Comment by bgruening** [comment]
Upps, fixed :)

**Comment by gallardoalba** [comment]
> Upps, fixed :)

Thanks u!

**Pull request merged**
