### PR TITLE
Cutadapt

### PR DESCRIPTION
**Pull request by eggzilla**

### CODE REVIEW

**Comment by eggzilla** [comment]
Please dont merge yet, still WIP

**Comment by bgruening** [comment]
Have you seen this one? https://toolshed.g2.bx.psu.edu/view/lparsons/cutadapt/01d94df2e32a
ping @lparsons yours is still maintained right?

**Comment by eggzilla** [comment]
Thanks!

**Comment by lparsons** [comment]
Yes, and actually @mblue9 is currently updating it and porting it over to the IUC tools: https://github.com/galaxyproject/tools-iuc/pull/1729/

**Comment by bgruening** [comment]
New cutadopt version is online and on usegalaxy.eu.
Sorry @eggzilla, I should have told you earlier.

**Pull request closed without merging**
