### PR TITLE
Update Music Compare

### PR DESCRIPTION
**Pull request by mtekman**
Implemented clustering+dendrograms for heatmaps, and fixed a parsing issue for dissimilar bulk datasets (spotted by @nomadscientist).

### CODE REVIEW

**Comment by mtekman** [comment]
I didn't bump the version on purpose, since it's only a change to the music_compare tool

**Comment by mtekman** [comment]
Actually, don't merge anything yet. I just realised a critical missing feature from the tools. I'll implement it as part of this PR today, and then I'll bump the versions

**Comment by bgruening** [comment]
Is this ready to go @mtekman ?

**Comment by mtekman** [comment]
@bgruening yes please!

**Review by bgruening — APPROVED** [review]

**Pull request merged**
