### PR TITLE
find_and_replace: column splitting bugfix

### PR DESCRIPTION
**Pull request by bernt-matthias**
perl split defaults to split on any space but we need to split by tab

### CODE REVIEW

**Comment by bgruening** [comment]
Can we add a test that fails with the old behavior and passes with the new one. This way we make sure it does not break anymore - and the tool number should be bumped.

**Comment by bernt-matthias** [comment]
Test has been added

**Comment by bernt-matthias** [comment]
failing test seems unrelated :(

**Comment by bgruening** [comment]
Yes, the linter can not lint this super complex patter of one of the very old tools ... however, it seems to work.

@bernt-matthias can you review and comment on https://github.com/bgruening/galaxytools/pull/841

I'm unsure if I should like it ... :(

I will then merge all PR together and release a new version of all these tools.

**Pull request merged**
