### PR TITLE
Sailfish update

### PR DESCRIPTION
**Pull request by bgruening**
Latest version of sailfish.

### CODE REVIEW

**Comment by bgruening** [comment]
Still not sure if it's worth to write a data manager for it, as the transcriptome changes too frequently and a fixed index does not make so much sense. Currently, the admin can link in manually a reference transcriptome. I think it makes sense to make the history-transcriptome default.
Any opinions? 

ping @nsoranzo @nekrut @jennaj

**Comment by jennaj** [comment]
All makes sense. @blankenberg is a good person to help make the final decision.

**Comment by nsoranzo** [comment]
Never used sailfish, sorry, I have no informed opinion!

**Comment by bgruening** [comment]
Release early release often. Hopefully, this is good enough.

**Pull request merged**
