### PR TITLE
Condafy uniprot_rest_interface

### PR DESCRIPTION
**Pull request by nsoranzo**
Also:
- Fix typos in two `<test>`s.
- Use 'detect_errors' instead of `<stdio>`.
- Update test-data.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks Nicola! It's seems 2 tests are failing - is this some random behavior?

**Comment by nsoranzo** [comment]
Yes, it seems the order of the entries in the FASTA and GFF files are random, I can use `sim_size` or do you have other suggestions?

**Comment by bgruening** [comment]
sime_size should work or include, I would favor simsize.

**Comment by bgruening** [comment]
Thanks a lot!

**Pull request merged**
