### PR TITLE
shows warnings to give a user a fighting chance

### PR DESCRIPTION
**Pull request by bwlang**
re #331

### CODE REVIEW

**Comment by bwlang** [comment]
I think this resolves the tests...
I applied planemo normalize, hope that's what you want
One potential concern, I don't know what "set compressed = 'no'" does, i just kept it from your upstream changes.

**Comment by bgruening** [comment]
@bwlang planemo normalise does nothing good at the moment, can you revert this commit? It just scrambles the order of attributes and removes &&

**Comment by bgruening** [comment]
Thanks for working on this.

**Comment by bwlang** [comment]
this fails local tests... may gzip differences. i'll push one more to loosen up the size comparisons a bit.

**Comment by bwlang** [comment]
ok... maybe this is ok for you?

**Comment by bgruening** [comment]
Thanks a bunch @bwlang!

**Pull request merged**
