### PR TITLE
minor fix for NSPDK inputs

### PR DESCRIPTION
**Pull request by mmiladi**

### CODE REVIEW

**Comment by mmiladi** [comment]
@bgruening This could make us save a few hours :D

**Comment by mmiladi** [comment]
could u pls merge this? thanks

**Comment by bgruening** [comment]
Why is this saving some hours?

**Comment by mmiladi** [comment]
Before I was merging gspan collection files and then split and vectorize them. For mega files it started to become significant. This option let me to skip gspan merging.

**Pull request merged**
