### PR TITLE
Updating tools/bioimaging from version 2.3.1 to 2.4.0

### PR DESCRIPTION
**Pull request by gxydevbot**
Hello! This is an automated update of the following tool: **tools/bioimaging**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/bioimaging from version 2.3.1 to 2.4.0.

**Project home page:** https://github.com/bgruening/galaxytools/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by SaimMomin12** [comment]
Can this be already merged?

**Comment by bgruening** [comment]
Sure, we trust our tests :)

**Comment by bgruening** [comment]
@SaimMomin12 if you trust the tests as well please:

* check if a profile version in included
* any other obvious change should happen ... maybe adding `creators`
* and then feel free to merge it on your own

**Comment by SaimMomin12** [comment]
@bgruening have checked the below points, they are already included in the tool :)

- [x] check if a profile version in included
- [x] any other obvious change should happen ... maybe adding creators

**Pull request merged**
