### PR TITLE
bump flye to 2.9.3

### PR DESCRIPTION
**Pull request by thanhleviet**
- bumped flye to 2.9.3
- fixed missing scaffolding in test
- updated test assertion

### CODE REVIEW

**Comment by bgruening** [comment]
@thanhleviet unfortunately it still fails.

**Comment by thanhleviet** [comment]
@bgruening
How can I see the tool_test_output.html ?
```
There were problems with 5 test(s) - out of 9 test(s) executed. See tool_test_output.html for detailed breakdown.
flye (Test #1): passed
flye (Test #2): passed
flye (Test #3): passed
flye (Test #4): failed
flye (Test #5): failed
flye (Test #6): failed
flye (Test #7): failed
flye (Test #8): failed
flye (Test #9): passed
```
All of these tests passed on my local VM, using `planemo 0.75.19` as well.
[tool_test_output.html.zip](https://github.com/bgruening/galaxytools/files/13753139/tool_test_output.html.zip)

**Comment by bgruening** [comment]
Try running planemo test --biocontainers ... The planemo output is also available here on GitHub at the gh actions summery page

**Comment by thanhleviet** [comment]
Ran with `planemo t --biocontainers`, it pulled `quay.io/biocontainers/flye:2.9.3--py310h2b6aa90_0`,  and no fails at all
[tool_test_output.html.zip](https://github.com/bgruening/galaxytools/files/13755237/tool_test_output.html.zip)
So no idea why it failed on here 🧐
I couldn't find tool_test_output.html under that action summary page as well.

**Comment by bgruening** [comment]
On this page https://github.com/bgruening/galaxytools/actions/runs/7299218189?pr=1372 scroll down to `All tool test results `. Download those artefacts.

**Comment by bgruening** [comment]
```
Output assembly_info:  different than expected
Expected text '418681' in output ('#seq_name	length	cov.	circ.	repeat	mult.	alt_group	graph_path
contig_1	418704	17	N	N	1	*	*,1,*
')

**Comment by bgruening** [comment]
grafik

**Comment by thanhleviet** [comment]
lol, flye results are so ridiculously stochastic

**Comment by bgruening** [comment]
@thanhleviet I think I know whats going on here. Flye just needs way more memory than the CI provides. So this failes here randomly. I pushed an update to master after testing locally.

Thanks @thanhleviet

**Comment by thanhleviet** [comment]
Thank you @bgruening , but indeed Flye does not perform consistently, see https://rrwick.github.io/2024/02/15/misassemblies.html
> Misassembly 2: Listeria welshimeri 
The second misassembly happened with [Listeria welshimeri ATCC-35897](https://www.atcc.org/products/35897) ([reads here](https://trace.ncbi.nlm.nih.gov/Traces/?run=SRR27638395)), where Flye deleted a 3956 bp chunk of the genome. George first noticed it when running [hybracter](https://github.com/gbouras13/hybracter) (which uses Flye), and he saw that the deletion occurred about 70% of the time. I tried to replicate the problem on my computer, and I found it to depend on thread count: using 1 thread or 5+ threads resulted in a correct contig (no deletion) while using 2–4 threads resulted in the deletion.[6](https://rrwick.github.io/2024/02/15/misassemblies.html#fn:threads)

**Pull request closed without merging**
