### PR TITLE
Fixed 2 bugs: 1) when the primary metric is default, it must be repla…

### PR DESCRIPTION
**Pull request by kxk302**
…ced by classification/regression default metric, and 2) Need  to undo OHE of labels for validation set

### CODE REVIEW

**Comment by kxk302** [comment]
Hi @anuprulez,

With the change in this PR, I managed to pass both failing test cases. I'll test this on FNN, RNN, and CNN workflows. Could you also please test it any relevant workflow you have? Thanks!

**Comment by bgruening** [comment]
The tests are failing @kxk302

**Comment by bgruening** [comment]
Can you please bump the tool version?

**Comment by kxk302** [comment]
> Can you please bump the tool version?

Bumped the bug fix version up.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Will be deployed over the weekend.

**Pull request merged**
