### PR TITLE
canu

### PR DESCRIPTION
**Pull request by mmiladi**

### CODE REVIEW

**Comment by mmiladi** [comment]
@bgruening Can we set $GALAXY_SLOTS for planemo test local and/or on travis?

https://travis-ci.org/bgruening/galaxytools/jobs/388795343#L2148

**Comment by bgruening** [comment]
Why that. Sorry only have my cell phone.

**Comment by mmiladi** [comment]
No worries thx. Have ur time. In progress.

**Comment by mmiladi** [comment]
Now only the test where single output is generated fails:
https://travis-ci.org/bgruening/galaxytools/jobs/388997295#L1833

**Comment by mmiladi** [comment]
Passed :dancing_men:

**Comment by bgruening** [comment]
Muha! Thanks for pushing this over the line! Will install it as soon as I have real network access.

**Comment by mmiladi** [comment]
Refinements still needed. ho hurries :) Thanks.

**Pull request merged**
