### PR TITLE
miRDeep2 mapper: add support for multiple input files

### PR DESCRIPTION
**Pull request by abretaud**
Hey,
A little modification to allow giving miRDeep2 mapper a list of multiple input read sets.
I would have preffered to use a `multiple="true"` data param and use element_identifier as sample names, but it turns out mirdeep2 only supports 3 letter sample names.
Cheers

### CODE REVIEW

**Comment by abretaud** [comment]
@bgruening thanks for 9ce6e1d! I'm also preparing a little patch for mirdeep2, I'll push it to this PR

**Comment by bgruening** [comment]
Thanks to you @abretaud!

**Comment by bgruening** [comment]
I'm fine with the old way :) Thanks!

**Comment by bgruening** [comment]
Thanks!

**Comment by bgruening** [comment]
Yeah, planemo can not deal really good with multiple users. I upload them manually.

**Comment by bgruening** [comment]
Done.

**Comment by abretaud** [comment]
Cool, looks good for mirdee2, but not mirdeep2_mapper, maybe you forgot it? (or I'm too impatient ;))

**Comment by bgruening** [comment]
Internet is not that fast here :)

**Comment by bgruening** [comment]
Done.

**Comment by abretaud** [comment]
ahah, sorry, I was too impatient :) thanks
Hope you're enjoying South Africa!

**Pull request merged**
