### PR TITLE
Wrapped mlxtend market basket analysis (MBA) tools

### PR DESCRIPTION
**Pull request by kxk302**
So, Galaxy has MBA support. Use fpgrowth to generate frequent itemsets (more performant than apriori algorithm), based on a support filter. Then generated asociation rules via association_rules, based on confidence, lift, and conviction filters.

### CODE REVIEW

**Comment by kxk302** [comment]
Cleaned up the code a bit. This is ready for review now. Thanks.

**Review by bgruening — APPROVED** [review]

**Comment by kxk302** [comment]
@bgruening Can this be merged? Thanks

**Comment by bgruening** [comment]
Yes :) Sorry!

**Comment by kxk302** [comment]
> Yes :) Sorry!

Thanks @bgruening!

**Pull request merged**
