### PR TITLE
diffbind: optional control

### PR DESCRIPTION
**Pull request by scholtalbers**
in addition reformatted a bit to make planemo lint happy. 
Generating test data is somewhat difficult, ran this on big samples which seemed to work as expected.
Basically this removes the control column when no control is found. It will however fail unclean when only a few samples have a control and some not... but I wasn't sure how much code can/should but squeezed in the configfile section

### CODE REVIEW

**Comment by bgruening** [comment]
Uh, awesome! Yes test data is tricky for this one. Sorry. One reason I keep it here and not under IUC.
Can you please increase the tool-version?

Thanks!
Bjoern

**Comment by scholtalbers** [comment]
done

**Comment by bgruening** [comment]
Uh sorry, I forgot about this one. @scholtalbers please don't hesitate to ping me more often!

**Comment by bgruening** [comment]
TS updated!

**Comment by scholtalbers** [comment]
no apologies needed! However, I don't seem to find the updated version in TS or TTS? In addition, I noticed I restructured the help with headers, this might not be wished as the show up quite large in Galaxy?

**Comment by scholtalbers** [comment]
ping @bgruening

**Comment by bgruening** [comment]
Oo, now? :)
Btw. what are you doing between the 5. and 8. of April? I will do a Galaxy-dev workshop/hackathon in HD. Do you want to help :)

**Pull request merged**
