### PR TITLE
PCA tools

### PR DESCRIPTION
**Pull request by lorrainealisha75**

### CODE REVIEW

**Comment by simonbray** [comment]
Great, tests are passing - thanks @lorrainealisha75

**Comment by khanteymoori** [comment]
Thanks, @lorrainealisha75 and @simonbray 
It looks perfect now

**Comment by bgruening** [comment]
the shed.yml files was missing. So it was not tested and never pushed :(
Sorry.

**Comment by simonbray** [comment]
It was tested, e.g. here: https://travis-ci.org/github/bgruening/galaxytools/jobs/716856425

I think a shed file is not needed as it's in the sklearn subfolder.

**Comment by bgruening** [comment]
I see, ok, Then I need to look why this was not pushed ...

**Comment by simonbray** [comment]
> I see, ok, Then I need to look why this was not pushed ...

Okay, thanks a lot!

**Comment by kxk302** [comment]
@simonbray @lorrainealisha75 
Hi, I was wondering if sklearn PCA tool is available for use in Galaxy EU or Galaxy Main? When I search for PCA, I find other tools (e.g., R-based, which does not seem to work), but I cannot find the sklearn version. Thanks for your help!

**Comment by simonbray** [comment]
Hi @kxk302, it should have been installed on usegalaxy.eu, but it seems there was some problem as mentioned by Björn above: https://github.com/usegalaxy-eu/usegalaxy-eu-tools/commit/8a85fd8596db89cdb9a96982ca41f9b0ef3830e2#diff-ac9a5a5abe56f7f694dbef62fb65ca82

@bgruening do you remember / did you work out what the matter was?

**Comment by kxk302** [comment]
Thanks @simonbray

**Comment by simonbray** [comment]
This never got pushed to the toolshed for some reason. What is the best solution? @bgruening can you do it manually? Or can we get the CI to do it by opening a new PR?

**Pull request merged**
