### PR TITLE
strip-it

### PR DESCRIPTION
**Pull request by HassanAmr**
removed strip-it from the blacklist

### CODE REVIEW

**Comment by bgruening** [comment]
I think I know what it is: strip-it was compiled again openbabel-2.3 but now `openbabel-2.3.90dev7d621d9` gets installed. We need to fix the conda package and strictly depend on openbabel-2.3

**Comment by HassanAmr** [comment]
In bioconda? am I allowed to just change someone else's package there?

**Comment by bgruening** [comment]
Sure ;)

**Comment by HassanAmr** [comment]
The package strictly depends on openbabel-2.3.2 (openbabel ==2.3.2). Why does it install 2.3.90?

**Comment by bgruening** [comment]
It turns out that there is a newer version of strip_it that is not installable with the old version of conda `3.19.3`. If you use a newer version of conda you will get the latest, fixed version.

To use a newer conda version this needs to be fixed: https://github.com/conda/conda/issues/2035

**Pull request closed without merging**
