### PR TITLE
Chipseeker raises error when 'no' is selected in the plots boolean

### PR DESCRIPTION
**Pull request by ccedmendoza**
- Added test to check if the tool runs when no plot output is selected
- Modified wrapper so that the test passes

### CODE REVIEW

**Comment by ccedmendoza** [comment]
You're welcome. Could it be possible to push the new version to the toolshed, please?

**Comment by bgruening** [comment]
Keep an eye on https://travis-ci.org/bgruening/galaxytools/builds/463371568 the push happens automatically as soon as the tests have passed again on the master branch. I will monitor this and make sure its ends up there.

**Comment by ccedmendoza** [comment]
ok, thank you.

**Comment by bgruening** [comment]
Ok, you are ready to go! :)

**Pull request merged**
