### PR TITLE
removed shape-it from the blacklist

### PR DESCRIPTION
**Pull request by HassanAmr**

### CODE REVIEW

**Comment by HassanAmr** [comment]
Hi Björn,
So, should I keep continuing within the same pull request the rest of the packages, or should I wait for it to merge, then push a new change?

**Comment by bgruening** [comment]
Test failed with a core dump :(

**Comment by HassanAmr** [comment]
So, how should I proceed? should I revert back the changes, and try a new package?

**Comment by bgruening** [comment]
Leave this one open. This needs to be solved at some point. Not sure why it crashes, maybe the conda package is broken? Or the input is strange. If you want to work further one some other tool please use different branches.

**Comment by HassanAmr** [comment]
Ok, I'll continue with each package in its own new branch. would it be ok if I continue tomorrow? Because I have to prepare for my trip tomorrow.

**Pull request merged**
