### PR TITLE
WIP: Imagej2

### PR DESCRIPTION
**Pull request by HassanAmr**
I will try to get the tools in this folder off the blacklist

### CODE REVIEW

**Comment by bgruening** [comment]
Does this work for you locally? I think these tools can not be tested with the local Galaxy job runner, only a real one, which is not the default one in planemo - means we can not tests these reliably.

**Comment by HassanAmr** [comment]
Doesn't this mean it tested ok?
https://travis-ci.org/HassanAmr/galaxytools/builds/242672706

**Comment by bgruening** [comment]
It was testing something yes (no clue why), but if you look at the tools that are tested - its not imageJ.

**Comment by HassanAmr** [comment]
Ok, I will revisit this maybe in the future

**Pull request closed without merging**
