### PR TITLE
bamhash

### PR DESCRIPTION
**Pull request by HassanAmr**
removed bamhash from the blacklist

### CODE REVIEW

**Comment by bgruening** [comment]
Only bamhash 1.0 seems to be available: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bamhash/meta.yaml

**Comment by HassanAmr** [comment]
can I just edit it?

**Comment by HassanAmr** [comment]
I think that might be the problem with many of the packages I just released.... is it possible to manually just edit the version in the xml file?

**Comment by bgruening** [comment]
A new conda package would be nice

**Comment by HassanAmr** [comment]
Ok, for this one I will make a new conda package, but what about the ones that have version behind the conda version? can I just edit the version number?

**Comment by bgruening** [comment]
Yes. Upgrading the package is OK. Remember if you do so increase the tool version number and remove the tool_dependencies.xml file.

**Comment by HassanAmr** [comment]
any convention I should follow when increasing the tool version?

**Comment by bgruening** [comment]
A version close or equal to the requirement version would be nice.
On Sep 3, 2016 3:41 AM, Hassan Gamaleldin <notifications@github.com> wrote:any convention I should follow when increasing the tool version?

**Comment by HassanAmr** [comment]
The bioconda package is already 1.0. Am I missing something?

**Comment by bgruening** [comment]
Yeah, but the tool requirement is 1.1 :)
I will change this!

**Comment by bgruening** [comment]
Hi @HassanAmr,

turns out the 1.1 version was correct: https://github.com/DecodeGenetics/BamHash/blob/dd15dee202b4d873768017b8959e8000d62ccf67/bamhash_checksum_common.h

Can you create a new conda package for the latest commit or maybe we will get soon a new release: https://github.com/DecodeGenetics/BamHash/issues/7

**Comment by HassanAmr** [comment]
Hi @bgruening,

So, this should work now?

**Comment by bgruening** [comment]
I get crazy: |  /tmp/tmp5O2hMi/job_working_directory/000/10/tool_script.sh: line 9: bamhash_checksum_fastq: command not found

**Comment by HassanAmr** [comment]
Sorry, this one was obviously failing because I forgot to remove the dependecies xml file

**Comment by bgruening** [comment]
The tool_dependencies.xml has nothing to do with this, still not clear for me what happend, but everything is green so let's merge!
Thanks!

**Comment by HassanAmr** [comment]
My pleasure :)

**Pull request merged**
