### PR TITLE
Replace SCRIPT_PATH with `$__tool_directory__` 

### PR DESCRIPTION
**Pull request by bgruening**
This will fix https://github.com/bgruening/galaxytools/issues/85

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think you forgot to remove `CRISPR_RECOGNITION_TOOL_SCRIPT_PATH` set_to action in ` galaxytools/tools/crt/tool_dependencies.xml` .

**Comment by bgruening** [comment]
@nsoranzo hah, thanks! Your review skills are impressive!
@jmchilton is this a devil?

**Comment by jmchilton** [comment]
"smiling imp" - I thought the emoji might convey the intention better than [mwahahaha](http://www.oxforddictionaries.com/us/definition/american_english/mwahahaha). 

Also - yes @nsoranzo is amazing - we need to somehow create a command-line version of him so we can apply these checks before committing.

**Comment by bgruening** [comment]
:+1: :)

**Comment by nsoranzo** [comment]
:laughing:

**Pull request merged**
