### PR TITLE
Diff add -y parameter

### PR DESCRIPTION
**Pull request by RZ9082**
We should still consider making the HTML report to be dependent of `-y` and `-unified` in my opinion.

### CODE REVIEW

**Comment by bgruening** [comment]
> We should still consider making the HTML report to be dependent of `-y` and `-unified` in my opinion.

Not sure what this means, but please do :)
or in the next version?

**Comment by bgruening** [comment]
Do you know why diff raises a non 0 error code? You can also do `diff ---fooo | true` I think. But its a hack, better to figure put why diff is behaving like that.

**Comment by RZ9082** [comment]
> Do you know why diff raises a non 0 error code? You can also do `diff ---fooo | true` I think. But its a hack, better to figure put why diff is behaving like that.

when files do not differ the diff tool returns exit code 0, when they do differ it exits with code 1. exit code 2 would mean an error.

**Comment by wm75** [comment]
would be good to add a comment like that above the line of code

**Comment by bgruening** [comment]
uha interesting, why did this not fail us before? Thanks @RZ9082 for figuring this out!

**Comment by bgruening** [comment]
Ah, that was the reason the profile did not work. Cool!

Please add this as a comment and we can merge :)

**Comment by RZ9082** [comment]
> Ah, that was the reason the profile did not work. Cool!
> 
> Please add this as a comment and we can merge :)

Exactly.
Comment added. Thanks!

**Review by bgruening — APPROVED** [review]

**Pull request merged**
