### PR TITLE
upgrade and extend nanopolish

### PR DESCRIPTION
**Pull request by mmiladi**

### CODE REVIEW

**Comment by mmiladi** [comment]
PR regarding issue https://github.com/bgruening/galaxytools/issues/867

**Comment by mmiladi** [comment]
@bgruening What could be wrong with the second reference?

citation nanopolish

**Comment by bgruening** [comment]
What do you mean, which tool is that?

**Comment by mmiladi** [comment]
There are two citations for nanopolish in the macros file. The second one has not been rendered properly in usegalaxy (screenshot) and i don’t know why

**Comment by mmiladi** [comment]
@bgruening looks good?

**Comment by mmiladi** [comment]
We can add support for `fast5.tar` here, beside .gz one.  (if this format is a valid galaxy format)

**Comment by bgruening** [comment]
All three are valid formats.https://github.com/galaxyproject/galaxy/blob/dev/config/datatypes_conf.xml.sample#L273

**Comment by mmiladi** [comment]
> Can we get draft_single_seq.fa smaller?

It's shortened.

**Comment by bgruening** [comment]
I'm still not sure what you mean with the reference? It exactly what we have in bibtex: https://github.com/bgruening/galaxytools/pull/868/files#diff-f5f3b985aa2daf3371ef5668dd200e1dR25

We should remove this isn't it?

**Comment by mmiladi** [comment]
> I'm still not sure what you mean with the reference? It exactly what we have in bibtex: https://github.com/bgruening/galaxytools/pull/868/files#diff-f5f3b985aa2daf3371ef5668dd200e1dR25
> 
> We should remove this isn't it?

Hmm, I am blind :D

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
