### PR TITLE
Update mafft.xml

### PR DESCRIPTION
**Pull request by DamCorreia**
use "change_format" to change the output format

### CODE REVIEW

**Comment by bgruening** [comment]
@DamCorreia this is great! Thanks a lot!
Can you please increase the version number of the tool?

**Comment by DamCorreia** [comment]
@bgruening   You're welcome ! Should I put 7.221.2 as the version number ?

**Comment by bgruening** [comment]
Yes please! :)

**Comment by DamCorreia** [comment]
It's done ;)

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
