### PR TITLE
Peakachu

### PR DESCRIPTION
**Pull request by TorHou**
One could add more help. But I'm not an expert on these parameters, so ... it works and could be improved if anybody aside from us wants to use it.

### CODE REVIEW

**Comment by bgruening** [comment]
.shed.yml file is missing

**Comment by TorHou** [comment]
ugh.. sure

**Comment by bgruening** [comment]
@TorHou how could the test pass, with this bug? Can we add it test that is catching those bugs ;)

**Comment by TorHou** [comment]
It occurs when there are more than one experimental and one control library .. The test case has one e-lib and one c-lib .. that's why it worked there

**Comment by bgruening** [comment]
Danke!

**Pull request merged**
