### PR TITLE
Text processing

### PR DESCRIPTION
**Pull request by HassanAmr**

### CODE REVIEW

**Comment by HassanAmr** [comment]
linting awk.xml locally doesn't produce any errors, can we retry the test please?

**Comment by bgruening** [comment]
Seems to be a legit failure on the cut tool.

```
```
ERROR: Invalid tmpZ_eDCM found. Errors [/tmp/tmpZ_eDCM:72:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'conditional': This element is not expected. Expected is ( action ).]
```

**Comment by HassanAmr** [comment]
Yes, cut.xml has a problem. I mean awk.xml

**Comment by bgruening** [comment]
Oh I see, it has a URL that is linted, so planemo is checking if all URLs are valid and it seems this line : http://www.ibm.com/developerworks/linux/library/l-awk1.html is not valid :)

**Comment by bgruening** [comment]
Can you try this one: http://www.ibm.com/developerworks/linux/library/l-awk1/index.html

**Comment by HassanAmr** [comment]
It worked, thanks :)

**Pull request merged**
