### PR TITLE
add NGL Protein Viewer as Galaxy visualization

### PR DESCRIPTION
**Pull request by bgruening**
NGL Viewer: a web application for molecular visualization
-------------------------------------------------------------------------------

NGL Viewer is a web application for molecular visualization. WebGL is employed to display molecules like proteins and DNA/RNA with a variety of representations. NGL is developed by [Alexander Rose](https://github.com/arose).

To reference this tool please cite:
  * NGL Viewer: a web application for molecular visualization
   [10.1093/nar/gkv402](http://nar.oxfordjournals.org/content/early/2015/04/28/nar.gkv402.abstract)

The source is MIT licensed and hosted under https://github.com/arose/ngl

Thanks @arose!

### CODE REVIEW

**Comment by erasche** [comment]
@bgruening is there a tool to download PDB files?

**Comment by bgruening** [comment]
Working on this as part of the [ChemicalToolBox project](https://github.com/bgruening/galaxytools/tree/master/chemicaltoolbox). Working on proper [datatypes for cheminformatics](https://github.com/bgruening/galaxytools/blob/master/chemicaltoolbox/datatypes/datatypes_conf.xml) and want to get them into Galaxy before adding data sources.

**Comment by erasche** [comment]
Thanks for the heads up, my boss will love this.

**Comment by blankenberg** [comment]
Just came here to say "awesome".

**Comment by bgruening** [comment]
@blankenberg NGL in action:
NGL Galaxy plugin

**Comment by erasche** [comment]
`:3`

**Comment by arose** [comment]
Thanks @bgruening it is great to see the NGL Viewer embedded in Galaxy! I imagine that this will be a very fruitful collaboration!

Also, dear Galaxians, if your browser allows non-Galaxy tabs :-) you can visit http://proteinformatics.charite.de/ngl/html/ngl.html?example=3pqr and see the NGL Viewer in action right-away.

**Pull request merged**
