### PR TITLE
tweak feature selection tool

### PR DESCRIPTION
**Pull request by qiagu**
This is follow-up of PR #723. Thanks to @jgoecks. 

1) remove cheetah style and change to pure python for easier interpretation.
2) move feature selection UI element to macro, making it able to be used in other tool.

### CODE REVIEW

**Comment by bgruening** [comment]
@qiagu is this replacing #732?

**Comment by qiagu** [comment]
No, we actually want both. How to change the git structure of my PR?

**Comment by bgruening** [comment]
you need to rebase now against latest master :)

**Comment by qiagu** [comment]
Yes, I need do that.

**Comment by qiagu** [comment]
@bgruening Could you please resolve the conflicts by keeping the changes from sk_new?

**Comment by bgruening** [comment]
Can you check please :)

**Comment by qiagu** [comment]
Perfect. Thanks.

**Comment by bgruening** [comment]
Thanks a bunch!

**Pull request merged**
