### PR TITLE
Add confusion matrix to Machine Learning Visualization Extension tool

### PR DESCRIPTION
**Pull request by anuprulez**
This PR adds an option (within `Machine Learning Visualization Extension` tool) to create confusion matrix viz to measure performances of machine learning and deep learning methods. It uses `matplotlib` to export the `PNG` plot of confusion matrix. 

This would be useful to showcase the performance of the neural networks in introductory deep learning tutorial based on the following analysis (cancer classification using gene expression):
https://github.com/anuprulez/gene_exp_deep_learning/blob/master/predict_cancer_deep_learning.ipynb

cnfmat

### CODE REVIEW

**Comment by anuprulez** [comment]
@khanteymoori can you look at it? Thanks!

**Comment by anuprulez** [comment]
@bgruening Done. I am wondering how the failing test is related to this PR

**Comment by bgruening** [comment]
It probably isn't ... just the numerical instability in all this ML ...

Can you fix the test ... you just need to adjust the 5.xxx in the one test case.

**Comment by anuprulez** [comment]
Checking now

**Comment by anuprulez** [comment]
I removed the fourth precision of the number that was getting tested as it was coming uncertain every time I checked. 

`5.5986` -> `5.598`

**Comment by anuprulez** [comment]
@bgruening all tests passed

**Comment by anuprulez** [comment]
Thanks!!!

**Pull request merged**
