### PR TITLE
Use new sed Conda package. Linting fixes. Fix requirements

### PR DESCRIPTION
**Pull request by nsoranzo**
Remove broken links.

### CODE REVIEW

**Comment by nsoranzo** [comment]
@jmchilton Linting of `tools/text_processing/text_processing/cut.xml` fails probably due to nested conditional in `tool > outputs > data > actions > conditional > when > conditional` and/or https://github.com/galaxyproject/galaxy/issues/3213.

@bgruening Planemo tests pass for me locally, do you want to merge this anyway?

**Comment by bgruening** [comment]
Sure! @nsoranzo do you keep track of this XSD bug?

**Comment by nsoranzo** [comment]
galaxyproject/galaxy#3213 has just been fixed by @jmchilton in https://github.com/galaxyproject/galaxy/pull/3216 , the conditional nesting is just a guess, will have to wait for a Planemo update to verify.

Do you want an issue here or in some other repo?

**Comment by bgruening** [comment]
I don't really care, just that we don't forget it. I need to find time to mass update all tools here to pass linting at some point. Thanks @nsoranzo

**Pull request merged**
