### PR TITLE
Update Music compare

### PR DESCRIPTION
**Pull request by mtekman**
Updated music_deconvolution tool so that it can now seperate between the two methods it uses

Added a new tool music_compare that can deconvolute and compare multiple bulk datasets

******

I'm unable to rebase this to upstream master, since the history I have did not squash my previous commits. Not sure how to fix this.

### CODE REVIEW

**Comment by bgruening** [comment]
@mtekman this was not easy to merge, please have a look at tools/music_deconvolution/scripts/estimateprops.R and check this carefully with your local version. I might have messed things up.

Also a parameter compare_title has been removed, is that correct?

**Comment by mtekman** [comment]
@bgruening thanks -- I tried merging it myself, but ran into similar issues (and I'm sorry for all the work!)

I found a nice solution online for rebasing onto a specific commit (keyword: `--onto`)

````
git checkout music_compare
git rebase --onto master 7a416140d0adfd12e6043367590abaa35ad53b87
```

and somehow everything rebased nicely

**Comment by mtekman** [comment]
@bgruening  Okay, I'm happy with this. It runs on everything I throw at it. I think it's ready to be merged

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Cool, wonderful work, also in the training. Do you need them today?

**Comment by mtekman** [comment]
Ideally yes, since @nomadscientist only has time to record the trainings this week

**Comment by bgruening** [comment]
@mtekman done

**Pull request merged**
