### PR TITLE
RNAcode: eps output disabled per default

### PR DESCRIPTION
**Pull request by bernt-matthias**
For larger fasta files the number of eps files generated overloads galaxy, so I changed the default to "not generate pictures". For users that still want the pictures I added the option to generate a single multipage eps / tar.gz. I'm happy to remove this again if you think its not necessary, since it requires ghostscript as additional dependency. I guess for larger fasta files nobody will look at the pictures anyway.

In our example for a human chromosome nearly 40000 eps file = 6GB are generated. Now our Galaxy is busy integrating them: 

```
...
Created dynamic collection dataset for path [/work/songalax/galaxy-dev/database/jobs_directory/004/4073/working/eps/hss-16840.eps] with element identifier [hss-16840] for output [hss-16840] (734.055 ms)
...
```

Btw. any idea how to stop this .. our Galaxy is nearly unusable meanwhile :(

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Sorry, I branched from the diamond branch. Maybe a rebase helps?

**Comment by bgruening** [comment]
@jmchilton would be interested in this I guess. He is currently optimizing this :)

**Comment by bgruening** [comment]
A rebase would help yes, or we merge the Diamond one ... let me check, was anything missing in diamond?

**Comment by bernt-matthias** [comment]
@jmchilton looking at the time spent for each data set it appeared that it got larger during time, but this might also be due to our cluster. started at 1s per data set and went up to 4s. 

will try to rebase tomorrow.

**Comment by bernt-matthias** [comment]
Can can do anything to make travis happy. Seemingly it does not know about the level fatal_oom in stdio.

**Comment by bernt-matthias** [comment]
@bgruening do I need to increase profile in order to make fatal_oom work?

**Comment by bgruening** [comment]
I just added a commit to use latest Galaxy release for testing. But adding a profile would be also good.

**Comment by bernt-matthias** [comment]
hmm. timeout for the ncbi ftp. link works.

**Comment by bgruening** [comment]
I tried to rerun, but it still fails. Not its even two links :(

**Comment by bernt-matthias** [comment]
Hmm, this is just linting, which is failing for two links in the help section. Can we disable this somehow? Or can I add some restructuredtext magic that helps?

**Comment by bgruening** [comment]
It tried to run it locally, but it seems `eps.tar.gz` is missing.

**Comment by bernt-matthias** [comment]
rebase messed this one up: close in favour of https://github.com/bgruening/galaxytools/pull/814

the eps.tar.gz is already present in master. no idea whats going on.

**Pull request closed without merging**
