### PR TITLE
Add dewseq tool

### PR DESCRIPTION
**Pull request by michauhl**
Add Galaxy wrapper for DEWSeq, a sliding window based peak caller for CLIP-seq data (especially eCLIP / iCLIP):
https://bioconductor.org/packages/release/bioc/html/DEWSeq.html

### CODE REVIEW

**Comment by michauhl** [comment]
Arrggh, that's not fair, I'm only writing a wrapper around this R markdown script. Now I need to fix all the 300+ linter errors there :/

**Comment by bgruening** [comment]
@michauhl if this script is not from you, package it up in conda.

**Comment by michauhl** [comment]
@bgruening problem is that the linter complains about things I cannot change, e.g., "Variable and function name style should be snake_case or symbols" for function names of the library itself. I can adapt the R markdown script code, but not the library code.

**Comment by michauhl** [comment]
@bgruening okay, it seems it only complains about variable or function names inside script. So I probably can fix the linter errors on my own ....

**Comment by michauhl** [comment]
@bgruening there seems to be a problem with creating an HTML report file (file not found):
https://github.com/bgruening/galaxytools/actions/runs/3281632111/jobs/5403948901#step:7:1478
The R script (analyseStudy.Rmd) should create the HTML report file, the python script (dewseq_wrapper.py) is the wrapper that calls the R script. Any idea why HTML can cause a problem here? I tried local "planemo test" and "planemo serve", no problems here.

**Comment by michauhl** [comment]
The R script is somehow unable to write a file:
https://github.com/bgruening/galaxytools/actions/runs/3281632111/jobs/5403948901#step:7:1470

```
|  label: session info
|  Error in file(con, "w") : cannot open the connection
|  Calls: <Anonymous> -> <Anonymous> -> write_utf8 -> writeLines -> file
|  In addition: Warning message:
|  In file(con, "w") :
|  cannot open file 'analyseStudy.knit.md': Read-only file system
|  Execution halted
```
If you have no other ideas, I will remove outputting the HTML report file altogether.

**Comment by bgruening** [comment]
Do you know where this script tries to write? We test here in containers and the only directory you are allowed to write is the `working directory`.

**Comment by michauhl** [comment]
No idea / could not find where where sessionInfo() stores intermediate files. Now trying with R script copying to working directory ...

**Comment by michauhl** [comment]
@bgruening Okay this works now. Next error is that the produced float numbers minimally differ from the ones produced on my computer. How to rewrite this test to just test whether the file is there? 
```
<output name="win_csv_file" file="windows.csv"/>
```
Or another idea how to test tables with many differing floating numbers inside?

**Comment by michauhl** [comment]
If nothing better, this one could do:
```
<output name="html_report_file" file="report.html" compare="sim_size"/>
```

**Comment by bgruening** [comment]
Sure you have many ways to test your ouputs: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-tests-test-output-assert-contents

https://docs.galaxyproject.org/en/latest/dev/schema.html#has-text-matching sounds good, or how many columns you expect etc ...

**Comment by michauhl** [comment]
Is there some manual on how to run the same testing procedure as here on my computer? (Docker image?)

**Comment by bgruening** [comment]
No tests for columns? You can now remove a few of the test files from the PR.

**Comment by michauhl** [comment]
@bgruening  Oooookkkkaaaaaaayyy ........

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Danke

**Comment by michauhl** [comment]
Super danke!

**Pull request merged**
