### PR TITLE
Lint all python files

### PR DESCRIPTION
**Pull request by simonbray**
I guess a lot of tests will fail, not necessarily because of the linting.

### CODE REVIEW

**Comment by simonbray** [comment]
Looks like the only tests which are failing here but passing in #1108 are `AREsite2_REST`, `antarna` and `ctb_chemfp_nxn_clustering`. (Tool linting also needs fixing)

**Comment by bgruening** [comment]
What about merging this PR but stopping the CI. So those changes gets only deployed when there is a real tool update in the future?

**Comment by simonbray** [comment]
> What about merging this PR but stopping the CI. So those changes gets only deployed when there is a real tool update in the future?

That sounds good to me, I just need to fix those failing tool tests as well :+1:

**Comment by simonbray** [comment]
Okay, all the tests are passing that were passing before, so we can merge IMO.

**Comment by bgruening** [comment]
Super cool, danke!

**Comment by bernt-matthias** [comment]
Hi @simonbray in order to make this sustainable we should add this to the CI workflow: https://github.com/bgruening/galaxytools/blob/ca87db9c038a6fcf96aa39da50f384865fd932ff/.github/workflows/pr.yaml#L168 .. (or replace flake8)

ideally starting at the IUC repo.

**Comment by simonbray** [comment]
I think the current `flake8` checks are fine. The problem was that most of the python code was failing linting because it was written before the CI checks were introduced. The aim of this PR was just to fix that.

**Pull request merged**
