### PR TITLE
shape-it

### PR DESCRIPTION
**Pull request by HassanAmr**
removed shape-it from the blacklist

### CODE REVIEW

**Comment by HassanAmr** [comment]
Hi @bgruening ,
I think this has the same problem as targetfinder.
```
Fatal error: Exit code 127 ()
/tmp/tmpO3jvBp/job_working_directory/000/3/tool_script.sh: line 9: shape-it: command not found
```

**Comment by bgruening** [comment]
I fixed the error. Can you run it locally and see if this example takes more than 10min?

**Comment by HassanAmr** [comment]
The error above is from my local. The branch is up-to-date with master. I just retried it now, and it is the same.

**Comment by bgruening** [comment]
The error is fixed, now it is timeout from travis. So I'm wondering if this test really takes 10 and more minutes.

**Comment by HassanAmr** [comment]
Locally, it takes about a minute, but it comes back with an error.

**Comment by HassanAmr** [comment]
Hi @bgruening,

I added the parameter --scoreOnly to skip performing the test. It exits with code 0, and it still processes all the parameters given in the test. But of course, the test is not meaningful in any way.
I also kept the old test output to revisit it later and check why it gets stuck while performing the test.

**Comment by HassanAmr** [comment]
Hi @bgruening,

Did I miss something in this branch?

**Comment by HassanAmr** [comment]
I don't get it. It was fine before the rebase

**Comment by bgruening** [comment]
@HassanAmr this was a hack right? The binary is still crashing?

**Comment by HassanAmr** [comment]
@bgruening, it doesn't crash, it keeps running forever. So, I changed it to scoreOnly. Should I leave this open till I figure out the problem with this package?

**Comment by bgruening** [comment]
So essentially scoreOnly keeps looping? Is this reproducibly with other files?

**Comment by HassanAmr** [comment]
scoreOnly works (or it used to before I did the rebase). without scoreOnly it doesn't finish. I also tried CID_2244.sdf (from openbabel), and it also didn't finish.

**Comment by bgruening** [comment]
Included here: https://github.com/bgruening/galaxytools/pull/576/commits/c659c1553be79ff3590e4543af8ed009d0d5f481

**Pull request closed without merging**
