### PR TITLE
Uniprot: remove duplicated options, check response status

### PR DESCRIPTION
**Pull request by bernt-matthias**
On out instance we "often" get unexpected empty results. I guess checking the response status is a good idea.

Wondering also if we should

- add a timeout parameter https://2.python-requests.org/en/master/user/quickstart/#timeouts
- implement a retry mechanism (in some cases, e.g. timeout)
- if we should split the query also for the map case .. we try to map >50k entries.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Have seen the following exception in local tests. This could be a case for a retry:

```
|  Traceback (most recent call last):
|  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
|  (self._dns_host, self.port), self.timeout, **extra_kw)
|  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connec
| Peek:
|  *Peek unavilable.*
| Dataset Job Standard Output:
|  *Standard output was empty.*
| Dataset Job Standard Error:
|  Traceback (most recent call last):
|  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
|  (self._dns_host, self.port), self.timeout, **extra_kw)
|  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 56, in create_connection
|  for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
|  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
|  for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
|  socket.gaierror: [Errno -2] Name or service not known
|  During handling of the above exception, another exception occurred:
|  Traceback (most recent call last):
|  chunked=chunked)
|  self._validate_conn(conn)
|  conn.connect()
|  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
|  conn = self._new_conn()
|  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
|  self, "Failed to establish a new connection: %s" % e)
|  urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fe25be545d0>: Failed to establish a new connection: [Errno -2] Name or service not known
|  During handling of the above exception, another exception occurred:
|  Traceback (most recent call last):
|  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
|  timeout=timeout
|  _stacktrace=sys.exc_info()[2])
|  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
|  raise MaxRetryError(_pool, url, error or ResponseError(cause))
|  urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.uniprot.org', port=443): Max retries exceeded with url: /uploadlists/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe25be545d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
|  During handling of the above exception, another exception occurred:
|  Traceback (most recent call last):
|  File "/home/berntm/.planemo/planemo_tmp_bhfgwwjh/uniprot.py", line 76, in <module>
|  args.out.write(_retrieve(query, format=args.format))
|  File "/home/berntm/.planemo/planemo_tmp_bhfgwwjh/uniprot.py", line 30, in _retrieve
|  r = requests.post(url + tool, data=data, files={'file': ' '.join(_)})
|  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 112, in post
|  return request('post', url, data=data, json=json, **kwargs)
|  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 58, in request
|  return session.request(method=method, url=url, **kwargs)
|  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
|  resp = self.send(prep, **send_kwargs)
|  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
|  r = adapter.send(request, **kwargs)
|  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
|  raise ConnectionError(e, request=request)
|  requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.uniprot.org', port=443): Max retries exceeded with url: /uploadlists/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fe25be545d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by bgruening** [comment]
Any idea how we can do this? probably with a backoff?

**Comment by bernt-matthias** [comment]
> Any idea how we can do this? probably with a backoff?

This looks nice: https://findwork.dev/blog/advanced-usage-python-requests-timeouts-retries-hooks/ 

I will give it a try

**Comment by bernt-matthias** [comment]
Done. I tested this locally with data sets > 50000 entries. Do you know somebody at uniprot to check if our approach is good (timeouts, chunkting etc ... also I would like to know if there is a way to know if some IDs could not be mapped)?

**Comment by bgruening** [comment]
No, but maybe @hrhotz knows someone?

**Comment by hrhotz** [comment]
Most UniProt people I know, have moved on. I suggest to contact Alex (https://www.ebi.ac.uk/about/people/alex-bateman) - feel free to mention my name. He should be able to point you at the right person in his team.

**Comment by bernt-matthias** [comment]
Thanks @hrhotz mail is out. I put you in the CC

**Comment by bernt-matthias** [comment]
Hi. Here a summary of the mail communication with UniProt:

- There is a separate ID mapping server http://idmapping.uniprot.org which is the backend for https://www.uniprot.org/uploadlists/. But it does not provide the possibility for downloading data. 
- Timeout issues for https://www.uniprot.org/uploadlists/ are known. They are working on this. 

Not sure what to do about this. 

- We could switch to http://idmapping.uniprot.org for the mapping and leave fasta download with https://www.uniprot.org/uploadlists/ (but we may need separate code for this)
- Or we leave it as is .. and hope that my improvements in this PR make the download sufficiently stable

**Comment by bgruening** [comment]
> Or we leave it as is .. and hope that my improvements in this PR make the download sufficiently stable

This and see how far we come? ... and hope they fix it?

**Comment by bernt-matthias** [comment]
> This and see how far we come? ... and hope they fix it?

Jep. Still switching to http://idmapping.uniprot.org seem reasonable and we should open an issue here / add a TODO to the sources.

**Comment by bgruening** [comment]
let's ship it!

Danke @bernt-matthias!

**Pull request merged**
