### PR TITLE
fixed assert error

### PR DESCRIPTION
**Pull request by michauhl**
Just a small typo fix

### CODE REVIEW

**Comment by bgruening** [comment]
addition of short_ensembl looks more than a typo fix :) Is that intended?

**Comment by michauhl** [comment]
Yes this is needed, since before the FASTA IDs were cut after the "." in order to avoid certain annoyingly long FASTA IDs to invade the output tables. But to be compatible with optional BED input, by default the whole ID now get loaded.

**Comment by michauhl** [comment]
Is flake8 now mandatory?

"Unsuccessful tests found, inspect the 'All tool test results' artifact for details."
Where can I find these results?

**Comment by bgruening** [comment]
Yes, we enfore pep8 now. You see the results of testing in the github actions artefacts. 

grafik

**Comment by michauhl** [comment]
So all tests failed .. these not very informative (?)

grafik

**Comment by michauhl** [comment]
How to best break this under 80 characters?
```
    p = argparse.ArgumentParser(add_help=False,
                                prog="graphprot_predict_wrapper.py",
                                description=help_description,
                                formatter_class=argparse.MetavarTypeHelpFormatter)
```

**Comment by michauhl** [comment]
Fantastic, on my PC flake8 did not complain ...

**Comment by bgruening** [comment]
`tools/rna_tools/graphprot/gplib.py:145:19: E226 missing whitespace around arithmetic operator` this looks like a very common one :(

Can you check if all changes have been checked in?

**Comment by michauhl** [comment]
Different flake8 versions seem to complain about different things. Just checked here, on my Laptop vs. Desktop, different complaints ...

**Comment by michauhl** [comment]
```
if re.search(".+\.gz$", fasta_file):
```
W605 invalid escape sequence '\.' 
Is this suddenly forbidden? How to escape regex characters now?

**Comment by bgruening** [comment]
`if re.search(r".+\.gz$", fasta_file):` --> __r__

**Comment by bgruening** [comment]
raw-string

**Comment by michauhl** [comment]
Guess it's this I'm missing: flake8-import-order-0.18.1

**Comment by michauhl** [comment]
This is pretty weird, the tests work on my laptop.

**Comment by bgruening** [comment]
I will take care, thanks @michauhl

**Comment by michauhl** [comment]
Great thanks! And let me know, I'm curious what the problem is :)

**Comment by michauhl** [comment]
Hi Björn, don't accept yet, I found another GraphProt error (it crashes when lowercase sequences are used as input). Will fix that and push the revision here first ...

**Comment by bgruening** [comment]
@michauhl you are still testing I guess?

**Comment by michauhl** [comment]
No I fixed the issue. On my PC all the tests work.

**Comment by bgruening** [comment]
Es ist grün, Simon hat es gefixed. Es war ein Fehler im testsystem.

**Comment by michauhl** [comment]
Ok. alles klar. Danke für den Support :)

**Comment by bgruening** [comment]
Dauert, aber ca. einen Tag bis das alles in Galaxy ist.

**Pull request merged**
