### PR TITLE
Rcas upate

### PR DESCRIPTION
**Pull request by dyusuf**

### CODE REVIEW

**Comment by dyusuf** [comment]
@bgruening 

the travis test outputs error,  "unable to open connection to X11 display", though planemo test was successful locally.

It seems X11 is not supported by the Travis setting. Any suggestions?

**Comment by bgruening** [comment]
@dyusuf there is no X11 and you should not use it, Oo.
On HPC we will not have X11 libs or whatsoever. Can this be fixed?

**Comment by dyusuf** [comment]
The tool generates a self-contained html with dynamic figures and tables. It starts a PNG device where needs a X11 connection. I need to ask how we could get around of it.

**Comment by bgruening** [comment]
You can create PNG with the cairo backend, which does not use X11.

**Comment by dyusuf** [comment]
Thanks for the suggestion. I have passed the message to the guys.

**Comment by dyusuf** [comment]
@bgruening I communicated with the team. It appears that RCAS is able to run without X11 such as the case of RCAS webserver, http://rcas.mdc-berlin.de/, that the server does not have X11.

Then I tried to figure out the reason why during the travis testing, X11 was required.

Later I found out, there is no cairo in the conda package of R 3.3.1 even it was built with cairo. Please see the following,

> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE        TRUE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE       FALSE        TRUE        TRUE        TRUE 

I guess this is up to the r channel to fix.

**Comment by bgruening** [comment]
Is this runtime or compile time. I really hope this is runtime ;)
Can you depend on cairo or r-cairo and see if this solves your problem?

**Comment by dyusuf** [comment]
it is the run time.

but the issue should result from the compilation of the conda package of R 3.3.1. I checked the conda recipe of R 3.3.1, cario is included. Yet, we don't find cario.

Then I tried to separately install r-cario,  here is the output,
$ conda install r-cairo

The following packages will be UPDATED:

    r-cairo:       1.5_9-r3.3.1_0   r --> 1.5_9-r3.2.2_0a   r
    r-class:       7.3_14-r3.3.1_0  r --> 7.3_14-r3.2.2_0a  r
    r-codetools:   0.2_14-r3.3.1_0  r --> 0.2_14-r3.2.2_0a  r
    r-foreign:     0.8_66-r3.3.1_0  r --> 0.8_66-r3.2.2_0a  r
    r-kernsmooth:  2.23_15-r3.3.1_0 r --> 2.23_15-r3.2.2_0a r
    r-lattice:     0.20_33-r3.3.1_0 r --> 0.20_33-r3.2.2_0a r
    r-mass:        7.3_45-r3.3.1_0  r --> 7.3_45-r3.2.2_0a  r
    r-rpart:       4.1_10-r3.3.1_0  r --> 4.1_10-r3.2.2_0a  r
    r-spatial:     7.3_11-r3.3.1_0  r --> 7.3_11-r3.2.2_0a  r

The following packages will be DOWNGRADED due to dependency conflicts:

    r:             3.3.1-r3.3.1_0   r --> 3.2.2-0           r
    r-base:        3.3.1-3          r --> 3.2.2-0           r
    r-boot:        1.3_18-r3.3.1_0  r --> 1.3_17-r3.2.2_0a  r
    r-cluster:     2.0.4-r3.3.1_0   r --> 2.0.3-r3.2.2_0a   r
    r-matrix:      1.2_6-r3.3.1_0   r --> 1.2_2-r3.2.2_0a   r
    r-mgcv:        1.8_12-r3.3.1_0  r --> 1.8_9-r3.2.2_0a   r
    r-nlme:        3.1_128-r3.3.1_0 r --> 3.1_122-r3.2.2_0a r
    r-nnet:        7.3_12-r3.3.1_0  r --> 7.3_11-r3.2.2_0a  r
    r-recommended: 3.3.1-r3.3.1_0   r --> 3.2.2-r3.2.2_0    r
    r-survival:    2.39_4-r3.3.1_0  r --> 2.38_3-r3.2.2_0a  r

R was downgraded to R 3.2.2, then,
> capabilities('cairo')
cairo 
 TRUE 

**Here is something wrong with cario in R 3.3.1.**

**Comment by bgruening** [comment]
@dyusuf is this solved with recent R versions?

**Comment by dyusuf** [comment]
@bgruening I will check the status after getting the download numbers done. Hope it could work.

**Pull request closed without merging**
