### PR TITLE
Add Methyldackel

### PR DESCRIPTION
**Pull request by dpryan79**
This adds MethylDackel (formerly PileOMeth) version 0.2.1 and updates the wrapper with more (probably all, I haven't checked) of the command line options.

### CODE REVIEW

**Comment by dpryan79** [comment]
Ping @joachimwolff

**Comment by bgruening** [comment]
@dpryan79 what is the update strategy? Or shouldn't there be one? pileometh should be removed from Galaxy and deprecated from the TS? If not, you could simply rename the pileometh folder and change everything, besides the tool-id ... if the tool-id keeps the same, methyldackel becomes just a newer version of pileometh.

**Comment by dpryan79** [comment]
I'll remove the current PileOMeth folder and change the MethylDackel toolid to be the same. If that's all that's needed for this to appear as an update then that's the easiest way to go.

**Comment by dpryan79** [comment]
The rebase got a bit messy, but this seems to essentially have resulted in git catching most things as a folder rename.

**Comment by bgruening** [comment]
Great thanks, I will play around with this tm a little bit and update it on our instance.

**Pull request merged**
