### PR TITLE
Add options for output.

### PR DESCRIPTION
**Pull request by TorHou**
I need blockbuster output for the Peakcaller workflow.... :neutral_face:

### CODE REVIEW

**Comment by bgruening** [comment]
Can we please add some test for the new outputs?
Thanks :-)

**Comment by TorHou** [comment]
:beers:  ?

**Comment by bgruening** [comment]
sure :beer: for tests.

**Comment by TorHou** [comment]
:beers: I'll put it on the toolsheds and our server tomorrow

**Pull request merged**
