### PR TITLE
changes the way files are concating, now appending files one by one instead of altogether

### PR DESCRIPTION
**Pull request by anilthanki**
changes the way files are concating, now appending files one by one instead of altogether to avoid large command when a collection is too big

### CODE REVIEW

**Comment by anilthanki** [comment]
Hi @bgruening 

The error is for another tool called  `cut` not from my PR

Thanks

Anil

**Comment by bgruening** [comment]
Thanks @anilthanki!

**Comment by nsoranzo** [comment]
Thanks for the manual upload @bgruening !

**Comment by anilthanki** [comment]
Thanks, @bgruening for merging this quickly..

**Pull request merged**
