### PR TITLE
Add --auto strategy to mafft.

### PR DESCRIPTION
**Pull request by nsoranzo**

### CODE REVIEW

**Comment by bgruening** [comment]
Nice! Thanks!

**Comment by bgruening** [comment]
Can you increase the version number, or should I do it?

**Comment by bgruening** [comment]
On the other hand it does not change anything from the previous tool ... will merge, thanks!

**Comment by bgruening** [comment]
@nsoranzo I updated it. Thanks again.

**Comment by nsoranzo** [comment]
Thank you for pushing to the TS.

**Pull request merged**
