### PR TITLE
Comment for BioPython Conda

### PR DESCRIPTION
**Pull request by remimarenco**
Add the comment to let people know the requirement will try to be resolved using BioPython Conda: https://anaconda.org/anaconda/biopython

### CODE REVIEW

**Comment by bgruening** [comment]
+ you need to remove it from the blacklist

**Comment by remimarenco** [comment]
Thanks, as we were not in the same repo, I did not think it was useful :). Will do now

**Comment by bgruening** [comment]
Nice you found that my tests are not good :)

**Comment by bgruening** [comment]
@remimarenco can you rebase against master? I have added the missing test files.

**Comment by remimarenco** [comment]
Done ;)

**Comment by bgruening** [comment]
And tests are passing. Great!

**Pull request merged**
