### PR TITLE
Fix bug in split_file_to_collection

### LINKED ISSUE #1424: `Split file` doesn't include header in last dataset when called on rows
The tool doesn't include the header in the last row, so the resulting dataset is only a single line - see the example dataset here: https://usegalaxy.eu/api/datasets/4838ba20a6d86765d3fbd03294f83c9e/display?to_ext=tabular

This causes the problems in the parameter sweeps tested in this history: https://usegalaxy.eu/u/hechth/h/parameter-sweep-testing-hechth-202405-1-1

https://github.com/bgruening/galaxytools/blob/7e5c9f013821c8905f2c9c452a1f00891e3a0cfd/tools/text_processing/split_file_to_collection/split_file_to_collection.xml#L131

### PR DESCRIPTION
**Pull request by zargham-ahmad**
This PR includes the following:

- added condition to write header in the final record dataset, it was not previously written in the last dataset if the chunk size was 1
- added test

closes #1424

### CODE REVIEW

**Comment by hechth** [comment]
@bgruening I think this is ready to go :)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Looks good, can you please also fix the linting issues.

**Comment by hechth** [comment]
@bgruening could you rerun the CI please? :)

**Comment by bgruening** [comment]
Sure, can you reply in Matrix please :)

**Pull request merged**
