### PR TITLE
Trna

### PR DESCRIPTION
**Pull request by jfallmann**
updated trnascan, planemo test not successful, compares wrong files (tab with fasta), aragorn also WIP

### CODE REVIEW

**Comment by bgruening** [comment]
@jfallmann sorry but this targets again master correct?

**Comment by jfallmann** [comment]
@bgruening no this was for your trna branch, had no push rights, just a status update more or less

**Comment by bgruening** [comment]
But there are many changes in this branch that don't belong here.

**Comment by jfallmann** [comment]
stimmt, hatte einen merge mit dem master gemacht vorm pushen, hat sich aber eh erledigt

**Pull request closed without merging**
