### PR TITLE
update locarna suite; add wrappers

### PR DESCRIPTION
**Pull request by s-will**

### CODE REVIEW

**Comment by s-will** [comment]
Hey @bgruening,
This rather looks like some internal problem; nothing due to my wrappers, right? Could you please have a look.

**Comment by bgruening** [comment]
I hope not, internal problem are bad :)

**Comment by bgruening** [comment]
Indeed an internal github error as it seems. Runs now.

**Comment by bgruening** [comment]
Nice! Macros for the win!

**Comment by s-will** [comment]
thanks! that was quick :). Good that the internal error was not so bad after all.

**Pull request merged**
