### PR TITLE
Bismark 0.20.0

### PR DESCRIPTION
**Pull request by scholtalbers**
These include the changes of #776  but with the recently released 0.20.0

0.19.1 could be skipped or not ..

### CODE REVIEW

**Comment by bgruening** [comment]
Still fails linting, I'm not able to see the error yet...

**Comment by scholtalbers** [comment]
at least on the last commit its not the lint but the test failed due to the diff being larger https://travis-ci.org/bgruening/galaxytools/jobs/419094305#L1963

**Comment by bgruening** [comment]
Ok, got it. Thanks a lot @scholtalbers!

**Comment by scholtalbers** [comment]
Great! Thanks for fixing and merging!

**Pull request merged**
