### PR TITLE
upgrade graphclust wrapper depen

### PR DESCRIPTION
**Pull request by mmiladi**

### CODE REVIEW

**Comment by bgruening** [comment]
Macros can help with such PRs a lot. I might look at this ...

**Comment by mmiladi** [comment]
I have to check it locally first. Linting also fails. Which kind of macros do u mean?

**Comment by mmiladi** [comment]
PR seems to be ready for merge. If all the functional test with the docker instance went fine. For the next update I can make a common macro file. For the moment having them separated would be better for testing. Thanks.

**Comment by bgruening** [comment]
@mmiladi it was working before the new version comes in.
@mmiladi your dev workflow seems to be too complicated. Do you know that you can use the local conda package, which you have locally build for testing with planemo? No need to create any PR.

**Comment by bgruening** [comment]
Nice! Thanks a lot!

**Comment by mmiladi** [comment]
Thank you!

**Pull request merged**
