### PR TITLE
Updating tools/diff tool version(s)

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool repo: **tools/diff**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

Please see https://github.com/planemo-autoupdate/autoupdate for more information.

### CODE REVIEW

**Comment by bgruening** [comment]
this is your tool @davelopez  ;)

**Review by davelopez — APPROVED** [review]

**Comment by simonbray** [comment]
I'm not sure if multiple versions of this tool are really useful... we can consider putting this on the autoupdate skiplist if you think so too.

**Comment by davelopez** [comment]
Yeah, I don't think there will be many version changes either, actually for some reason I was using the previous diffutils version instead of the last, so the bot did a great job 😆 
You can add it to the skiplist if you like.

**Comment by simonbray** [comment]
> this is your tool @davelopez ;)

Another thought: if we added a 'maintainer' in the .shed.yml file, we could have automatic pings. But I guess some IUC policy has to be changed for this again.

**Pull request merged**
