### PR TITLE
rnashapes

### PR DESCRIPTION
**Pull request by HassanAmr**
removed rnashapes from the blacklist

### CODE REVIEW

**Comment by bgruening** [comment]
We need an rnashapes 3.2.5 package for this tool.

**Comment by HassanAmr** [comment]
Is it ok to take if from https://launchpad.net/~bibi-help/+archive/ubuntu/bibitools/+sourcepub/4853756/+listing-archive-extra?

**Comment by bgruening** [comment]
The tarball? Yes. But it is also OK to just take the latest and update the tool.

**Comment by HassanAmr** [comment]
But shouldn't I update the bioconda recipe before updating it here?

**Comment by bgruening** [comment]
Yes :-)
On Aug 30, 2016 3:07 PM, Hassan Gamaleldin <notifications@github.com> wrote:But shouldn't I update the bioconda recipe before updating it here?

**Comment by HassanAmr** [comment]
Hi Björn,
I'm having problems installing rnashapes using the tar provided in the link above.
I tried following what is written here (I fail in the first step):
https://github.com/galaxyproject/starforge/blob/master/rnashapes/build.sh

But it didn't work as per the following:

make[3]: Entering directory '/tmp/tmp.j0RDGY9fZo'
make[3]: out.mf: No such file or directory
make[3]: *** No rule to make target 'out.mf'.  Stop.
make[3]: Leaving directory '/tmp/tmp.j0RDGY9fZo'
install: cannot stat '/tmp/tmp.j0RDGY9fZo/out': No such file or directory
make[2]: *** [../../..//makefile:89: compile] Error 1
make[2]: Leaving directory '/home/hassan/anaconda3/conda-bld/work/rnashapes_3.2.5/rnashapes/Misc/Applications/RNAshapes'
make[1]: *** [makefile:27: mfe_nodangle] Error 2
make[1]: Leaving directory '/home/hassan/anaconda3/conda-bld/work/rnashapes_3.2.5/rnashapes/Misc/Applications/RNAshapes'
make: *** [makefile:8: all] Error 2
make: Leaving directory '/home/hassan/anaconda3/conda-bld/work/rnashapes_3.2.5/rnashapes/Misc/Applications/RNAshapes'
Command failed: /bin/bash -x -e /home/hassan/anaconda3/conda-bld/work/rnashapes_3.2.5/conda_build.sh

Do I need to install the packages that are installed in the example I'm trying to follow as well? Because the rnashapes package doesn't need dependencies in the version on Bioconda.

The branch I'm working on is here:

https://github.com/HassanAmr/bioconda-recipes/tree/rnashapes_3_2_5

**Comment by bgruening** [comment]
RNAshapes is gone from the blacklist, so this one can really be closed.

**Pull request closed without merging**
