### PR TITLE
rnashapes

### PR DESCRIPTION
**Pull request by HassanAmr**
removed rnashapes from the blacklist

### CODE REVIEW

**Comment by bgruening** [comment]
@HassanAmr you have commits from other branches in your PR. Make sure you branch always from master.

**Comment by HassanAmr** [comment]
Oh, right. Sorry. But I always undid the change from the last PR, should I still redo them?

**Comment by bgruening** [comment]
Usually you only have the commits in one branch that counts. This will lead to merge conflicts later one I think.

**Comment by HassanAmr** [comment]
Should I delete them now, and redo the branches from the master. or should I wait, and resolve the issues first, and then delete and redo them?

**Comment by bgruening** [comment]
Don't delete them :) Try to rebase them or remove the unnecessary commits, I can explain you this offline if you want.

**Comment by HassanAmr** [comment]
Yes, that would be great :)... for the rest, I'll branch always from master (that means checkout from there, right?)

**Comment by bgruening** [comment]
Yes, `checkout -b new_branch_name`

**Pull request closed without merging**
