### PR TITLE
Adding GPU parameters for instaGRAAL

### PR DESCRIPTION
**Pull request by gulsumgudukbay**
Added GPU parameters for instaGRAAL to allow execution of the GPU-supported version of instaGRAAL.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @gulsumgudukbay! Since which Galaxy version is this supported? I guess we would need to add a profile version? Or we simply assume that older Galaxy will ignore it?

**Comment by bgruening** [comment]
ping @sanjaysrikakulam

**Comment by gulsumgudukbay** [comment]
> Thanks @gulsumgudukbay! Since which Galaxy version is this supported? I guess we would need to add a profile version? Or we simply assume that older Galaxy will ignore it?

It is supported after 23.0 (since the packages were released in that version). Could you please elaborate on the profile version? is it a specification for the Galaxy version for the requirements?

**Comment by bgruening** [comment]
See here: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-profile

**Comment by gulsumgudukbay** [comment]
> See here: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-profile

I added the profile tag

**Comment by gulsumgudukbay** [comment]
> See here: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-profile

Do I have to do anything else for the tests?

**Comment by gulsumgudukbay** [comment]
I think the profile version gave an error. I fixed it.

**Comment by bgruening** [comment]
Not yet, 23.1 is not yet released officially. Sorry.

**Comment by gulsumgudukbay** [comment]
> Not yet, 23.1 is not yet released officially. Sorry.

I also tried 23.0 (commit ID [6ba97a4]), however, that also gave an error (Lint tool-list test). I see that 23.0 is in the link you provided. 
Could you please let me know why it throws an error and how I can solve the issue?

**Comment by mvdbeek** [comment]
> Or we simply assume that older Galaxy will ignore it?

That's not an assumption, I would add your regular profile version. The linting is unrelated to those changes here.

**Comment by gulsumgudukbay** [comment]
> > Or we simply assume that older Galaxy will ignore it?
> 
> That's not an assumption, I would add your regular profile version (was it one year from the last stable release ?). The linting is unrelated to those changes here.

So 23.0 profile version should be correct?

**Comment by mvdbeek** [comment]
You don't technically need 23.0. I'd make it 22.01 if you want to follow https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#tool-profile

**Comment by gulsumgudukbay** [comment]
> You don't technically need 23.0. I'd make it 22.01 if you want to follow https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html#tool-profile

But the GPU tags are released in the 23.0 Galaxy version. If I make the profile 22.01, will it comply with the 23.0 Galaxy version changes? (I thought the profile and Galaxy version are related)

**Comment by mvdbeek** [comment]
> But the GPU tags are released in the 23.0 Galaxy version.

So they'll be ignored, that's ok.

**Comment by gulsumgudukbay** [comment]
> > But the GPU tags are released in the 23.0 Galaxy version.
> 
> So they'll be ignored, that's ok.

I updated the profile.

**Comment by gulsumgudukbay** [comment]
> See here: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-profile

Hi Bjorn, could you please re-trigger the tests if everything looks fine (also for the racon PR)?

**Comment by gulsumgudukbay** [comment]
The linting fails because there are two parameters with the same name ("bomb" parameter). Since it is unrelated to the GPU tags, I am not sure how to proceed. @bgruening  @mvdbeek

**Comment by bgruening** [comment]
Thanks @gulsumgudukbay !

**Pull request merged**
