### PR TITLE
[WIP] Add PathoScope

### PR DESCRIPTION
**Pull request by gallardoalba**
PathoScope is a pipeline to rapidly and accurately remove host contamination, isolate microbial reads, and identify potential disease-causing pathogens.

Screenshot from 2022-05-16 14-16-20

### CODE REVIEW

**Comment by gallardoalba** [comment]
It is not a real priority for now, so I'll close it until required.

**Comment by EngyNasr** [comment]
@gallardoalba can we reopen the PR I am thinking of adding the tool to the FoodBorne workflows, I need to identify pathogens, so either I do it with mapping with Minimap2, then Mpileup then variant annotation or do it with pathoscope, I currently reading more about the tool and which papers used the tool

**Comment by gallardoalba** [comment]
I left it behind because it makes a lot of use of databases, so I preferred to leave it for now, but it is almost finished I think @EngyNasr

**Comment by EngyNasr** [comment]
@gallardoalba I cannot thank you enough for everything, I guess the tool is very useful, instead of having the databases in MInimap and annotation afterwards the models of PathoMap and PathoDB can do that hopefully :)

**Comment by gallardoalba** [comment]
> @gallardoalba I cannot thank you enough for everything, I guess the tool is very useful, instead of having the databases in MInimap and annotation afterwards the models of PathoMap and PathoDB can do that hopefully :)

Will you work on that PR finally @EngyNasr?

**Pull request closed without merging**
