### PR TITLE
Fix for PeakPickerHiRes

### PR DESCRIPTION
**Pull request by blankclemens**
Fix for PeakPickerHiRes. Check OpenMS/OpenMS#2358 for more details.

### CODE REVIEW

**Comment by bgruening** [comment]
Is this because of the brackets?

**Comment by blankclemens** [comment]
Yes. To make it an automatic solution, what are your thoughts about quoting all parameters in general?

**Comment by bgruening** [comment]
In general all type=data and type=text should be quoted, but with single-quotes.
We can not quote all parameters, this will probably fail on booleans and integers, isn't it?

**Comment by blankclemens** [comment]
Single-quotes would be fine as well of course. So yes, that would be an easy solution, I just thought there might be a reason why CTD2Galaxy is not quoting these parameters at the moment - well, why quote something which is automatically defined anyways.

But since numbers should be flagged as such, quoting all text and data parameters might just do it without side effects.

**Comment by bgruening** [comment]
If we really think it's worth to spend more time in this we should not create the command section at all and use <configfiles>.

**Comment by blankclemens** [comment]
What exactly do you mean with "use ."?  Create an INI file for every job and load this one?

**Comment by bgruening** [comment]
Galaxy has a configfile option that we can use to create this ini file very easily. But I think this is too much work.

**Pull request merged**
