### PR TITLE
Bump Galaxy ML version to 0.10.0

### PR DESCRIPTION
**Pull request by anuprulez**
ping @bgruening

### CODE REVIEW

**Comment by bgruening** [comment]
That needs some more work I think :(

**Comment by anuprulez** [comment]
Hi @kxk302 @paulzierep, I will need some help in upgrading Galaxy ML tools to the latest version (0.10.0). All tests of many tools should be updated and probably all the model files as the format of the saved model got changed from H5/Zip to H5MLM. I have done for several tools but still many are remaining. 

The repo where I am stashing all the changes is: https://github.com/anuprulez/galaxytools/tree/fix_galaxy_ml_1.0

Here is the list of all tools for which tests are still failing:

❌ sklearn_clf_metrics (Test #11)
❌ sklearn_clf_metrics (Test #15)
❌ sklearn_clf_metrics (Test #6)

❌ sklearn_data_preprocess (Test #2)
❌ sklearn_data_preprocess (Test #3)
❌ sklearn_data_preprocess (Test #4)
❌ sklearn_data_preprocess (Test #5)
❌ sklearn_data_preprocess (Test #6)
❌ sklearn_data_preprocess (Test #7)
❌ sklearn_data_preprocess (Test #8)

❌ sklearn_discriminant_classifier (Test #1)
❌ sklearn_discriminant_classifier (Test #2)
❌ sklearn_discriminant_classifier (Test #3)
❌ sklearn_discriminant_classifier (Test #4)
❌ sklearn_discriminant_classifier (Test #5)
❌ sklearn_discriminant_classifier (Test #6)

❌ sklearn_ensemble (Test #1)
❌ sklearn_ensemble (Test #2)
❌ sklearn_ensemble (Test #11)
❌ sklearn_ensemble (Test #12)
❌ sklearn_ensemble (Test #3)
❌ sklearn_ensemble (Test #4)
❌ sklearn_ensemble (Test #5)
❌ sklearn_ensemble (Test #6)
❌ sklearn_ensemble (Test #7)
❌ sklearn_ensemble (Test #8)
❌ sklearn_ensemble (Test #9)
❌ sklearn_ensemble (Test #10)

❌ sklearn_generalized_linear (Test #1)
❌ sklearn_generalized_linear (Test #2)
❌ sklearn_generalized_linear (Test #11)
❌ sklearn_generalized_linear (Test #12)
❌ sklearn_generalized_linear (Test #13)
❌ sklearn_generalized_linear (Test #14)
❌ sklearn_generalized_linear (Test #15)
❌ sklearn_generalized_linear (Test #16)
❌ sklearn_generalized_linear (Test #3)
❌ sklearn_generalized_linear (Test #4)
❌ sklearn_generalized_linear (Test #5)
❌ sklearn_generalized_linear (Test #6)
❌ sklearn_generalized_linear (Test #7)
❌ sklearn_generalized_linear (Test #8)
❌ sklearn_generalized_linear (Test #9)
❌ sklearn_generalized_linear (Test #10)

❌ sklearn_lightgbm (Test #1)
❌ sklearn_lightgbm (Test #2)

❌ sklearn_model_fit (Test #1)
❌ sklearn_model_fit (Test #2)

❌ sklearn_nn_classifier (Test #1)
❌ sklearn_nn_classifier (Test #2)
❌ sklearn_nn_classifier (Test #3)
❌ sklearn_nn_classifier (Test #4)
❌ sklearn_nn_classifier (Test #5)
❌ sklearn_nn_classifier (Test #6)

❌ sklearn_numeric_clustering (Test #14)
❌ sklearn_numeric_clustering (Test #15)
❌ sklearn_numeric_clustering (Test #20)
❌ sklearn_pairwise_metrics (Test #2)

❌ sklearn_svm_classifier (Test #1)
❌ sklearn_svm_classifier (Test #2)
❌ sklearn_svm_classifier (Test #3)
❌ sklearn_svm_classifier (Test #4)
❌ sklearn_svm_classifier (Test #5)
❌ sklearn_svm_classifier (Test #6)

❌ sklearn_train_test_eval (Test #1)
❌ sklearn_train_test_eval (Test #2)
❌ sklearn_train_test_eval (Test #3)

Can you check and update the tests of these tools? Once these tests/tools are updated, we will need to adapt the training materials as well.

Let me know if you have questions!

Thanks a lot!

**Comment by kxk302** [comment]
Hi @anuprulez, I have a couple of deadlines and a bit busy, but will look next week.

**Comment by anuprulez** [comment]
Closing it in favour of https://github.com/bgruening/galaxytools/pull/1313

**Pull request closed without merging**
