### PR TITLE
diamond

### PR DESCRIPTION
**Pull request by HassanAmr**
removed diamond from the blacklist

### CODE REVIEW

**Comment by HassanAmr** [comment]
@bgruening, I think it fails to install diamond. What did I do wrong?

**Comment by HassanAmr** [comment]
Hi @bgruening, I will trigger a new Travis test as soon as diamond 0.8.24 is merged.

**Comment by bgruening** [comment]
ok, ping @bebatut as she was interested.
I think this wrapper needs a larger update

**Comment by bebatut** [comment]
I started to work on this wrapper. I will update it soon

**Comment by HassanAmr** [comment]
Hi @bgruening,

I should close and delete this PR/branch, right?

**Comment by bgruening** [comment]
Yeah!

**Pull request closed without merging**
