### PR TITLE
Uniq testing

### PR DESCRIPTION
**Pull request by bgruening**
A simple test case is needed.

ping @HassanAmr

### CODE REVIEW

**Comment by HassanAmr** [comment]
I'm on it

**Comment by nsoranzo** [comment]
Isn't this equivalent to https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/unsorted_uniq.xml ?

**Comment by bgruening** [comment]
Yes, just the very old version. I guess after this conda migration, I will deprecate this. Or do you think its ok to deprecate it now and remove it from the github.

**Comment by HassanAmr** [comment]
I'm also working on fixing the linting errors in text-processing. Should I wait on this one until you decide?

**Comment by bgruening** [comment]
It has for sure very low priority. I'm fine with deprecating it now, just wanted to be a good maintainer - at least one time :)

**Comment by HassanAmr** [comment]
How do I push to this pull request?

**Comment by nsoranzo** [comment]
If it has no future, I'd the deprecate it now. The sooner the better, in my opinion, no point in releasing a new version and then deprecate it. But it's your package, so your choice of course!

**Comment by HassanAmr** [comment]
linting awk.xml locally doesn't produce any errors, can we retry the test please?

**Comment by HassanAmr** [comment]
I commented in the wrong thread, sorry.

**Pull request merged**
