### PR TITLE
antarna

### PR DESCRIPTION
**Pull request by HassanAmr**
fixed lining errors for antarna

### CODE REVIEW

**Comment by bgruening** [comment]
Antarna is already in conda, do you mind to get it under testing?

**Comment by HassanAmr** [comment]
Done :)

**Comment by HassanAmr** [comment]
Oh, sorry, should have added tests first. Adding tests now.

**Comment by HassanAmr** [comment]
Mm, rnashapes 3.2.5 is a bit tricky, can we combine the sources retrieved from `hg clone ssh://hganon@hg.cebitec.uni-bielefeld.de/pi/software/gapc`, along with the contents of fold-grammars.zip (https://bibiserv2.cebitec.uni-bielefeld.de/fold-grammars/fold-grammars.zip) into a new tar online? This new tar will also provide the other tools within fold-grammars.

**Comment by bgruening** [comment]
Sure, submit your tarball to https://github.com/galaxyproject/cargo-port (the link), and we will give you a permanent link.

**Comment by HassanAmr** [comment]
Great, thanks.
I won't need it for antarna, but it appears a lot, and it is already on my ToDo list, so I will add it soon to bioconda.

**Comment by HassanAmr** [comment]
@bgruening,
can I also use your download_store to get a link?

**Comment by bgruening** [comment]
Sure!

**Comment by HassanAmr** [comment]
Thanks :)

**Comment by HassanAmr** [comment]
Does this need anything still? or is it ready to be merged?

**Comment by HassanAmr** [comment]
I can also remove the tool_dependencies.xml since it shouldn't be needed anymore

**Comment by bgruening** [comment]
Yes this can be removed as well.

**Pull request merged**
