### PR TITLE
Update antismash to v4.0.2

### PR DESCRIPTION
**Pull request by cmonjeau**
Hi @bgruening ,

on a direct order from @abretaud, here is a PR for Antismash :).

I changed the readme. rst but I'll let you finish.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @cmonjeau!

**Comment by bgruening** [comment]
I will probably use this tool to test Circle-CI soon :)
Thanks!

**Comment by abretaud** [comment]
Sweet!

**Comment by bgruening** [comment]
TTS/TS updated.

**Comment by bgruening** [comment]
deployed on usegalaxy.org - deployed not yet tested :)
Thanks @cmonjeau and @abretaud!

**Comment by cmonjeau** [comment]
Curently running on galaxy.genouest.org

image

**Comment by bgruening** [comment]
Super cool!

**Comment by cmonjeau** [comment]
And the first result

image

**Pull request merged**
