### PR TITLE
handle compressed files in trim galore

### PR DESCRIPTION
**Pull request by bgruening**
Patch by @dpryan79

### CODE REVIEW

**Comment by dpryan79** [comment]
I'm testing this currently. Should probably do that before merging :)

**Comment by dpryan79** [comment]
It looks like trim galore renames things if the input is gzipped. That's annoying and breaks the output file inclusion in Galaxy. I'll work on a fix.

**Comment by dpryan79** [comment]
I have a working version of this locally. I'll complete it and make a PR tomorrow. It's still kind of hacky (again with the `endswith(".gz")`, but it's better than nothing until galaxy starts handling compressed fastq files better.

**Comment by bgruening** [comment]
Ok, feel free to push against this branch. It has testing enabled.

**Pull request merged**
