### PR TITLE
graphclust conda version update. collect_result bug fixed.

### PR DESCRIPTION
**Pull request by eteriSokhoyan**

### CODE REVIEW

**Comment by mmiladi** [comment]
Hi @bgruening, is the toolshed updated? I rebuilt the docker bu I guess i didn't change he wrappers.

**Comment by bgruening** [comment]
Not yet, it's on my stack - soon very soon.

**Comment by mmiladi** [comment]
Thanks.

**Comment by bgruening** [comment]
TS updated and Galaxy instance as well. `dev` branch is also triggered.

**Pull request merged**
