### PR TITLE
Upgrade Fiji bUnwarpJ tools to version 20151222

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by bgruening** [comment]
Hi Greg, can you rebase this against master please. I messed up the travis testing.
Btw. what is the relation between this and https://github.com/bgruening/galaxytools/pull/424?

**Comment by gregvonkuster** [comment]
What command should I use to rebase it?  I've never had to do that before.  I can just drop this PR and add another if it would be easier.  https://github.com/bgruening/galaxytools/pull/424 includes upgrades for tools besides these bUnwarpJ tools.  The 2 PRs together include upgrades for all Fiji tools.

**Comment by bgruening** [comment]
in your branch, try to do a `git rebase master` :)

**Comment by gregvonkuster** [comment]
Doesn't seem to do anything.
```
$ git status
On branch bunwarpj

$ git rebase master
Current branch bunwarpj is up to date.
```

**Comment by bgruening** [comment]
Oh you need to pull the latest master at first. Or do `git rebase upstream/master`

**Comment by gregvonkuster** [comment]
@bgruening Sorry, rebasing against your upstream master just does not work:
```
]$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: Update travis testing
Using index info to reconstruct a base tree...
M	.travis.yml
Falling back to patching base and 3-way merge...
Auto-merging .travis.yml
CONFLICT (content): Merge conflict in .travis.yml
error: Failed to merge in the changes.
Patch failed at 0001 Update travis testing
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```
Attempting to fix the merge conflict:
```
$ git status
rebase in progress; onto 80da488
You are currently rebasing branch 'bunwarpj' on '80da488'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   .travis.yml

$ git add .travis.yml
(fiji) [greg@bigsky galaxytools]$ git rebase --continue
Applying: Update travis testing
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by bgruening** [comment]
That's how it should be. Do the rebase it will tell you that there are conflicts ... Git mergetool will help you to resolve it. Next git rebase --continue ... And then done.
I will just merge it thanks Greg! The flavour should do the testing for us.

**Comment by gregvonkuster** [comment]
Thanks @bgruening - so sorry for the hassles.... :(

**Comment by bgruening** [comment]
Uh, now we have a merge conflict. Can you resolve this or should I try? I guess from your other PR was something left over.

**Comment by gregvonkuster** [comment]
I think I'll just close this PR and open another that is clean.  ;)

**Pull request closed without merging**
