### PR TITLE
Update nanopolish to v0.13.2

### PR DESCRIPTION
**Pull request by DarianHole**
Small update to the newest nanopolish version

I don't believe there were any additional parameters added based on the changelog so just a version bump and some small fixes to test output data

### CODE REVIEW

**Comment by DarianHole** [comment]
Missed the most important spot ... I'll be back in a second

**Comment by DarianHole** [comment]
Tests seem to be failing due to small decimal changes in some of the fractions. Do you think I should add sim size with a small delta to the variant tests?

**Comment by bgruening** [comment]
What about adding some asserts? line_count, grepping for a line and so on?

**Comment by DarianHole** [comment]
That's a good idea, I'll do that. Anything else?

**Comment by bgruening** [comment]
No looks great! Thanks!

**Comment by bgruening** [comment]
Awesome!!!!

Thanks @DarianHole!

**Pull request merged**
