### PR TITLE
Adding GPU parameters for racon

### PR DESCRIPTION
**Pull request by gulsumgudukbay**
Added GPU parameters for racon to allow execution of the GPU supported version of racon.

### CODE REVIEW

**Comment by bgruening** [comment]
@gulsumgudukbay do you know when this extension was merged? Was it merged into 23.0 or dev?

**Comment by gulsumgudukbay** [comment]
> 23.0, but we still need to release packages.

Hi Marius, what do you mean by packages?

**Comment by bgruening** [comment]
Galaxy consists of many python packages and planemo the Galaxy SDK is using those packages. Since Galaxy 23.0 is not release we do not have those packages yet and planemo can is failing to lint your additions.

**Comment by gulsumgudukbay** [comment]
> Galaxy consists of many python packages and planemo the Galaxy SDK is using those packages. Since Galaxy 23.0 is not release we do not have those packages yet and planemo can is failing to lint your additions.

Hi @bgruening , are the tests triggered automatically whenever the packages are released?

**Comment by gulsumgudukbay** [comment]
> Galaxy consists of many python packages and planemo the Galaxy SDK is using those packages. Since Galaxy 23.0 is not release we do not have those packages yet and planemo can is failing to lint your additions.

I updated the profile to 22.01 as Marius told me in the Instagraal tool GPU tags (PR #1317 )

**Comment by gulsumgudukbay** [comment]
> Galaxy consists of many python packages and planemo the Galaxy SDK is using those packages. Since Galaxy 23.0 is not release we do not have those packages yet and planemo can is failing to lint your additions.

All tests have passed for racon tool. Do I have to do anything else for the merge?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
