### PR TITLE
Use profile version in text_processing tools

### PR DESCRIPTION
**Pull request by mvdbeek**
To get detect_errors="exit_code" and other good things.

### CODE REVIEW

**Comment by mvdbeek** [comment]
```
+Linting tool /home/travis/build/bgruening/galaxytools/tools/text_processing/text_processing/cut.xml
Applying linter tool_xsd... FAIL
.. ERROR: Invalid XML found in file: tmpqjKCNx. Errors [/tmp/tmpqjKCNx:72:0:ERROR:SCHEMASV:SCHEMAV_ELEMENT_CONTENT: Element 'conditional': This element is not expected. Expected is ( action ).]
```
That might be a valid error, I have no clue if this really works, it looks complicated.

**Comment by bgruening** [comment]
It really is complicated a relict I think from the very early days. I think it still works but it was never documented. Maybe @blankenberg knows more?

**Comment by bgruening** [comment]
ping @blankenberg

**Comment by bernt-matthias** [comment]
Some feedback for this old issue. I try to fix the linter issue over here: https://github.com/galaxyproject/galaxy/pull/15508

I agree that output actions are barely documented (a perfect example that non-trivial features that are not documented are not used xref https://github.com/galaxyproject/galaxy/pull/15027). But I also do not see how this is doing anything useful. 

```
                   <conditional name="delimiter">
                        <when value="T">
```

There is no value `"T"` for the delimiter parameter (and never was as far as I have seen). So this never did anything.

The second part that (if I get it right) tries to set column metadata which I don't see working correctly given that we remove columns. But due to the lack of docs I'm not sure. 

My suggestion would be to get rid of this or put some serious work into output actions (understanding code, adding docs and tests to the Galaxy code base .. I kind of feel tempted).

**Pull request closed without merging**
